# Clave JWT activa (puede venir de variable de entorno)
jwt.secret.key.active=${ENV=JWT_SECRET_KEY_ACTIVE:fPxXh1rOeBzB2n5lgPZwtsWmPN3x5GMEPqV4iCvu/YH2P+6J1iWv2EBEDQ57acCK}

# Clave JWT anterior (para validar tokens emitidos antes de rotar)
jwt.secret.key.previous=${ENV=JWT_SECRET_KEY_PREVIOUS:}

# Tiempo de expiración del token (1 hora = 3600000 ms)
jwt.expiration.ms=${ENV=JWT_EXPIRATION_MS:3600000}