package ec.com.tecnointel.soem.inventario.modelo;
// Generated 27/01/2016 10:21:32 by Hibernate Tools 4.3.1.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.validation.constraints.NotEmpty;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria")
// @NamedQuery(name="consultaCategoriaTodo",
// query="select categoria from Categoria categoria order by
// categoria.cateDescri")
public class Categoria implements java.io.Serializable {

	private static final long serialVersionUID = -3746688707777055226L;

	private Integer cateId;
	private String cateDescri;

	public Categoria() {
	}

	public Categoria(Integer cateId, String cateDescri) {
		this.cateId = cateId;
		this.cateDescri = cateDescri;
	}

	@Id
	@TableGenerator(name = "idCategoria", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "categoria", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idCategoria")
	@Column(name = "CATE_ID", unique = true, nullable = false)
	// @NotNull
	public Integer getCateId() {
		return this.cateId;
	}

	public void setCateId(Integer cateId) {
		this.cateId = cateId;
	}

	@Column(name = "CATE_DESCRI", nullable = false, length = 100, unique = true)
	@NotEmpty
	// Este Mensaje aparece cuando no se valida en la pagina => requiered =
	// "false"
	// @NotEmpty(message="Ingrese Descripci�n")
	// @NotNull
	public String getCateDescri() {
		return this.cateDescri;
	}

	public void setCateDescri(String cateDescri) {
		this.cateDescri = cateDescri;
	}

}