package ec.com.tecnointel.soem.inventario.modelo;
// Generated 12-jun-2017 11:10:38 by Hibernate Tools 5.2.0.Final

import java.time.LocalDate;
import java.time.LocalDateTime;

import ec.com.tecnointel.soem.egreso.modelo.EgreDeta;
import ec.com.tecnointel.soem.ingreso.modelo.IngrDeta;
import ec.com.tecnointel.soem.parametro.modelo.Bodega;
import ec.com.tecnointel.soem.parametro.modelo.Documento;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Kardex generated by hbm2java
 */
@Entity
@Table(name = "kardex")
public class Kardex implements java.io.Serializable {

	private Integer kardexId;
	private Sucursal sucursal;
	private Bodega bodega;
	private Documento documento;
	private EgreDeta egreDeta;
	private IngrDeta ingrDeta;
	private Producto producto;
	private LocalDate documeFech;
	private LocalDateTime documeFechHora;
	private Integer documeNume;

	private static final long serialVersionUID = -3320800528283412484L;

	public Kardex() {
	}

	public Kardex(Sucursal sucursal, Bodega bodega, Documento documento, Producto producto,  
			IngrDeta ingrDeta, EgreDeta egreDeta, Integer documeNume, LocalDate documeFech, LocalDateTime documeFechHora) {
		this.sucursal = sucursal;
		this.bodega = bodega;
		this.documento = documento;
		this.documeFech = documeFech;
		this.documeFechHora = documeFechHora;
		this.documeNume = documeNume;
		this.producto = producto;
		this.ingrDeta = ingrDeta;
		this.egreDeta = egreDeta;
	}

	@Id
	@TableGenerator(name = "idKardex", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "kardex", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idKardex")
	@Column(name = "KARDEX_ID", unique = true, nullable = false)
	public Integer getKardexId() {
		return this.kardexId;
	}

	public void setKardexId(Integer kardexId) {
		this.kardexId = kardexId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BODEGA_ID", nullable = false)
	public Bodega getBodega() {
		return bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENTO_ID", nullable = false)
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EGRE_DETA_ID")
	public EgreDeta getEgreDeta() {
		return this.egreDeta;
	}

	public void setEgreDeta(EgreDeta egreDeta) {
		this.egreDeta = egreDeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INGR_DETA_ID")
	public IngrDeta getIngrDeta() {
		return this.ingrDeta;
	}

	public void setIngrDeta(IngrDeta ingrDeta) {
		this.ingrDeta = ingrDeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_ID", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(columnDefinition = "DATE", name = "DOCUME_FECH", nullable = false, length = 10)
	public LocalDate getDocumeFech() {
		return documeFech;
	}

	public void setDocumeFech(LocalDate documeFech) {
		this.documeFech = documeFech;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "DOCUME_FECH_HORA", nullable = false, length = 19)
	public LocalDateTime getDocumeFechHora() {
		return documeFechHora;
	}

	public void setDocumeFechHora(LocalDateTime documeFechHora) {
		this.documeFechHora = documeFechHora;
	}

	@Column(name = "DOCUME_NUME", nullable = false)
	public Integer getDocumeNume() {
		return documeNume;
	}

	public void setDocumeNume(Integer documeNume) {
		this.documeNume = documeNume;
	}
}
