package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;

import ec.com.tecnointel.soem.parametro.modelo.Bodega;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdBode generated by hbm2java
 */
@Entity
@Table(name = "prod_bode")
@NamedEntityGraph(name = "prodBode.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "bodega"), 
@NamedAttributeNode(value = "producto") })
public class ProdBode implements java.io.Serializable {

	private Integer prodBodeId;
	private Bodega bodega;
	private Producto producto;
	private Sucursal sucursal;
	private BigDecimal cantidInic;
	private BigDecimal cantidActu;
	private BigDecimal cantidCont;
	private String ubicac;
	private BigDecimal maximo;
	private BigDecimal minimo;

	private static final long serialVersionUID = 5585580209952468150L;

	public ProdBode() {
	}

	public ProdBode(Integer prodBodeId, Bodega bodega, Producto producto, Sucursal sucursal, BigDecimal cantidInic,
			BigDecimal cantidActu, BigDecimal cantidCont, BigDecimal maximo, BigDecimal minimo) {
		this.prodBodeId = prodBodeId;
		this.bodega = bodega;
		this.producto = producto;
		this.sucursal = sucursal;
		this.cantidInic = cantidInic;
		this.cantidActu = cantidActu;
		this.cantidCont = cantidCont;
		this.maximo = maximo;
		this.minimo = minimo;
	}

	public ProdBode(Integer prodBodeId, Bodega bodega, Producto producto, Sucursal sucursal, BigDecimal cantidInic,
			BigDecimal cantidActu, BigDecimal cantidCont, String ubicac, BigDecimal maximo, BigDecimal minimo) {
		this.prodBodeId = prodBodeId;
		this.bodega = bodega;
		this.producto = producto;
		this.sucursal = sucursal;
		this.cantidInic = cantidInic;
		this.cantidActu = cantidActu;
		this.cantidCont = cantidCont;
		this.ubicac = ubicac;
		this.maximo = maximo;
		this.minimo = minimo;
	}

	@Id
	@TableGenerator(name = "idProdBode", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_bode", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdBode")
	@Column(name = "PROD_BODE_ID", unique = true, nullable = false)
	public Integer getProdBodeId() {
		return this.prodBodeId;
	}

	public void setProdBodeId(Integer prodBodeId) {
		this.prodBodeId = prodBodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BODEGA_ID", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_ID", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "CANTID_INIC", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCantidInic() {
		return this.cantidInic;
	}

	public void setCantidInic(BigDecimal cantidInic) {
		this.cantidInic = cantidInic;
	}

	@Column(name = "CANTID_ACTU", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCantidActu() {
		return this.cantidActu;
	}

	public void setCantidActu(BigDecimal cantidActu) {
		this.cantidActu = cantidActu;
	}

	@Column(name = "CANTID_CONT", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCantidCont() {
		return this.cantidCont;
	}

	public void setCantidCont(BigDecimal cantidCont) {
		this.cantidCont = cantidCont;
	}

	@Column(name = "UBICAC")
	public String getUbicac() {
		return this.ubicac;
	}

	public void setUbicac(String ubicac) {
		this.ubicac = ubicac;
	}

	@Column(name = "MAXIMO", nullable = false, precision = 12, scale = 6)
	public BigDecimal getMaximo() {
		return this.maximo;
	}

	public void setMaximo(BigDecimal maximo) {
		this.maximo = maximo;
	}

	@Column(name = "MINIMO", nullable = false, precision = 12, scale = 6)
	public BigDecimal getMinimo() {
		return this.minimo;
	}

	public void setMinimo(BigDecimal minimo) {
		this.minimo = minimo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bodega == null) ? 0 : bodega.hashCode());
		result = prime * result + ((producto == null) ? 0 : producto.hashCode());
		result = prime * result + ((sucursal == null) ? 0 : sucursal.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProdBode other = (ProdBode) obj;
		if (bodega == null) {
			if (other.bodega != null)
				return false;
		} else if (!bodega.equals(other.bodega))
			return false;
		if (producto == null) {
			if (other.producto != null)
				return false;
		} else if (!producto.equals(other.producto))
			return false;
		if (sucursal == null) {
			if (other.sucursal != null)
				return false;
		} else if (!sucursal.equals(other.sucursal))
			return false;
		return true;
	}

}
