package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdGrup generated by hbm2java
 */
@Entity
@Table(name = "prod_grup")
@NamedEntityGraph(name = "prodGrup.Graph", attributeNodes = { @NamedAttributeNode(value = "prodGrupNive") })
public class ProdGrup implements java.io.Serializable {

	private Integer prodGrupId;
	private ProdGrup prodGrup;
	private ProdGrupNive prodGrupNive;
	private String descri;
	private String tipo;

	private boolean moduloComp;
	private boolean moduloVent;
	private boolean moduloInve;

	private Boolean detall;
	private boolean estado;
	private Set<ProdGrup> prodGrups = new HashSet<ProdGrup>(0);
	private Set<Producto> productos = new HashSet<Producto>(0);
	private Set<ProdGrupPlanCuen> prodGrupPlanCuens = new HashSet<ProdGrupPlanCuen>(0);

	private static final long serialVersionUID = -7615743523163710991L;

	public ProdGrup() {
	}

	public ProdGrup(String tipo) {
		this.tipo = tipo;
	}

	public ProdGrup(String descri, String tipo, boolean moduloComp, boolean moduloVent, boolean moduloInve,
			Boolean detall, boolean estado) {
		super();
		this.descri = descri;
		this.tipo = tipo;
		this.moduloComp = moduloComp;
		this.moduloVent = moduloVent;
		this.moduloInve = moduloInve;
		this.detall = detall;
		this.estado = estado;
	}

	@Id
	@TableGenerator(name = "idProdGrup", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_grup", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdGrup")
	@Column(name = "PROD_GRUP_ID", unique = true, nullable = false)
	public Integer getProdGrupId() {
		return this.prodGrupId;
	}

	public void setProdGrupId(Integer prodGrupId) {
		this.prodGrupId = prodGrupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_GRUP_SUPE_ID")
	public ProdGrup getProdGrup() {
		return this.prodGrup;
	}

	public void setProdGrup(ProdGrup prodGrup) {
		this.prodGrup = prodGrup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROD_GRUP_NIVE_ID", nullable = false)
	public ProdGrupNive getProdGrupNive() {
		return this.prodGrupNive;
	}

	public void setProdGrupNive(ProdGrupNive prodGrupNive) {
		this.prodGrupNive = prodGrupNive;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "TIPO", nullable = false, length = 12)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "MODULO_COMP", nullable = false)
	public boolean isModuloComp() {
		return moduloComp;
	}

	public void setModuloComp(boolean moduloComp) {
		this.moduloComp = moduloComp;
	}

	@Column(name = "MODULO_VENT", nullable = false)
	public boolean isModuloVent() {
		return moduloVent;
	}

	public void setModuloVent(boolean moduloVent) {
		this.moduloVent = moduloVent;
	}

	@Column(name = "MODULO_INVE", nullable = false)
	public boolean isModuloInve() {
		return moduloInve;
	}

	public void setModuloInve(boolean moduloInve) {
		this.moduloInve = moduloInve;
	}

	@Column(name = "DETALL", nullable = false)
	public Boolean getDetall() {
		return detall;
	}

	public void setDetall(Boolean detall) {
		this.detall = detall;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodGrup")
	public Set<ProdGrup> getProdGrups() {
		return this.prodGrups;
	}

	public void setProdGrups(Set<ProdGrup> prodGrups) {
		this.prodGrups = prodGrups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodGrup")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodGrup")
	public Set<ProdGrupPlanCuen> getProdGrupPlanCuens() {
		return prodGrupPlanCuens;
	}

	public void setProdGrupPlanCuens(Set<ProdGrupPlanCuen> prodGrupPlanCuens) {
		this.prodGrupPlanCuens = prodGrupPlanCuens;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prodGrupId == null) ? 0 : prodGrupId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProdGrup other = (ProdGrup) obj;
		if (prodGrupId == null) {
			if (other.prodGrupId != null)
				return false;
		} else if (!prodGrupId.equals(other.prodGrupId))
			return false;
		return true;
	}
}
