package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;

import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdCost generated by hbm2java
 */
@Entity
@Table(name = "prod_cost")
@NamedEntityGraph(name = "prodCost.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "producto") })
public class ProdCost implements java.io.Serializable {

	private Integer prodCostId;
	private Producto producto;
	private Sucursal sucursal;
	private BigDecimal costoInic;
	private BigDecimal costoActu;
	private BigDecimal costoUlti;
	private BigDecimal costoCont;

	private static final long serialVersionUID = 7956015055623210889L;

	public ProdCost() {
	}

	public ProdCost(Integer prodCostId, BigDecimal costoInic, BigDecimal costoActu, BigDecimal costoUlti,
			BigDecimal costoCont) {
		this.prodCostId = prodCostId;
		this.costoInic = costoInic;
		this.costoActu = costoActu;
		this.costoUlti = costoUlti;
		this.costoCont = costoCont;
	}

	public ProdCost(Integer prodCostId, Producto producto, Sucursal sucursal, BigDecimal costoInic,
			BigDecimal costoActu, BigDecimal costoUlti, BigDecimal costoCont) {
		this.prodCostId = prodCostId;
		this.producto = producto;
		this.sucursal = sucursal;
		this.costoInic = costoInic;
		this.costoActu = costoActu;
		this.costoUlti = costoUlti;
		this.costoCont = costoCont;
	}

	@Id
	@TableGenerator(name = "idProdCost", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_cost", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdCost")
	@Column(name = "PROD_COST_ID", unique = true, nullable = false)
	public Integer getProdCostId() {
		return this.prodCostId;
	}

	public void setProdCostId(Integer prodCostId) {
		this.prodCostId = prodCostId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_ID")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID")
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "COSTO_INIC", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoInic() {
		return this.costoInic;
	}

	public void setCostoInic(BigDecimal costoInic) {
		this.costoInic = costoInic;
	}

	@Column(name = "COSTO_ACTU", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoActu() {
		return this.costoActu;
	}

	public void setCostoActu(BigDecimal costoActu) {
		this.costoActu = costoActu;
	}

	@Column(name = "COSTO_ULTI", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoUlti() {
		return this.costoUlti;
	}

	public void setCostoUlti(BigDecimal costoUlti) {
		this.costoUlti = costoUlti;
	}

	@Column(name = "COSTO_CONT", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoCont() {
		return this.costoCont;
	}

	public void setCostoCont(BigDecimal costoCont) {
		this.costoCont = costoCont;
	}

}
