package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.parametro.modelo.Dimm;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdDimm generated by hbm2java
 */
@Entity
@Table(name = "prod_dimm")
@NamedEntityGraph(name = "prodDimm.Graph", attributeNodes = {
@NamedAttributeNode(value = "producto"),
@NamedAttributeNode(value = "dimm") })
public class ProdDimm implements java.io.Serializable {

	private Integer prodDimmId;
	private Dimm dimm;
	private Producto producto;

	private static final long serialVersionUID = -5719858408236876724L;

	public ProdDimm() {
	}

//	public ProdDimm(Integer prodDimmId, Dimm dimm, Producto producto) {
//		this.prodDimmId = prodDimmId;
//		this.dimm = dimm;
//		this.producto = producto;
//	}

	public ProdDimm(Producto producto, Dimm dimm) {
		this.dimm = dimm;
		this.producto = producto;
	}

	@Id
	@TableGenerator(name = "idProdDimm", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_dimm", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdDimm")
	@Column(name = "PROD_DIMM_ID", unique = true, nullable = false)
	public Integer getProdDimmId() {
		return this.prodDimmId;
	}

	public void setProdDimmId(Integer prodDimmId) {
		this.prodDimmId = prodDimmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return this.dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_ID", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

}
