package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdGrupNive generated by hbm2java
 */
@Entity
@Table(name = "prod_grup_nive")
//@ValidadorTestInt
public class ProdGrupNive implements java.io.Serializable {

	private Integer prodGrupNiveId;
	private Integer nivel;
	private String descri;
	private Set<ProdGrup> prodGrups = new HashSet<ProdGrup>(0);

	private static final long serialVersionUID = 4164169509057962381L;

	public ProdGrupNive() {
	}

	public ProdGrupNive(Integer prodGrupNiveId, Integer nivel, String descri) {
		this.prodGrupNiveId = prodGrupNiveId;
		this.nivel = nivel;
		this.descri = descri;
	}

	public ProdGrupNive(Integer prodGrupNiveId, Integer nivel, String descri, Set<ProdGrup> prodGrups) {
		this.prodGrupNiveId = prodGrupNiveId;
		this.nivel = nivel;
		this.descri = descri;
		this.prodGrups = prodGrups;
	}

	@Id
	@TableGenerator(name = "idProdGrupNive", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_grup_nive", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdGrupNive")
	@Column(name = "PROD_GRUP_NIVE_ID", unique = true, nullable = false)
	public Integer getProdGrupNiveId() {
		return this.prodGrupNiveId;
	}

	public void setProdGrupNiveId(Integer prodGrupNiveId) {
		this.prodGrupNiveId = prodGrupNiveId;
	}

	@Column(name = "NIVEL", nullable = false)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodGrupNive")
	public Set<ProdGrup> getProdGrups() {
		return this.prodGrups;
	}

	public void setProdGrups(Set<ProdGrup> prodGrups) {
		this.prodGrups = prodGrups;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prodGrupNiveId == null) ? 0 : prodGrupNiveId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProdGrupNive other = (ProdGrupNive) obj;
		if (prodGrupNiveId == null) {
			if (other.prodGrupNiveId != null)
				return false;
		} else if (!prodGrupNiveId.equals(other.prodGrupNiveId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "ProdGrupNive [prodGrupNiveId=" + prodGrupNiveId + ", nivel=" + nivel + ", descri=" + descri + "]";
	}

}
