package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProdTipo generated by hbm2java
 */
@Entity
@Table(name = "prod_tipo")
public class ProdTipo implements java.io.Serializable {

	private Integer prodTipoId;
	private String descri;
	private boolean estado;
	private Set<ProdTipoPlanCuen> prodTipoPlanCuens = new HashSet<ProdTipoPlanCuen>(0);
	private Set<Producto> productos = new HashSet<Producto>(0);

	private static final long serialVersionUID = 7743229021404090386L;

	public ProdTipo() {
	}

	public ProdTipo(Integer prodTipoId, String descri) {
		this.prodTipoId = prodTipoId;
		this.descri = descri;
	}

	public ProdTipo(Integer prodTipoId, String descri, boolean estado, Set<ProdTipoPlanCuen> prodTipoPlanCuens,
			Set<Producto> productos) {
		this.prodTipoId = prodTipoId;
		this.descri = descri;
		this.estado = estado;
		this.prodTipoPlanCuens = prodTipoPlanCuens;
		this.productos = productos;
	}

	@Id
	@TableGenerator(name = "idProdTipo", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prod_tipo", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProdTipo")
	@Column(name = "PROD_TIPO_ID", unique = true, nullable = false)
	public Integer getProdTipoId() {
		return this.prodTipoId;
	}

	public void setProdTipoId(Integer prodTipoId) {
		this.prodTipoId = prodTipoId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodTipo")
	public Set<ProdTipoPlanCuen> getProdTipoPlanCuens() {
		return this.prodTipoPlanCuens;
	}

	public void setProdTipoPlanCuens(Set<ProdTipoPlanCuen> prodTipoPlanCuens) {
		this.prodTipoPlanCuens = prodTipoPlanCuens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prodTipo")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prodTipoId == null) ? 0 : prodTipoId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProdTipo other = (ProdTipo) obj;
		if (prodTipoId == null) {
			if (other.prodTipoId != null)
				return false;
		} else if (!prodTipoId.equals(other.prodTipoId))
			return false;
		return true;
	}

}
