package ec.com.tecnointel.soem.inventario.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * ProdPrec generated by hbm2java
 */

public class ProdComp implements java.io.Serializable {

	private String sucursal;
	private String cedula;
	private String proveedor;
	private LocalDate fechaEmis;
	private Integer numeroFact;
	private BigDecimal cantidad;
	private BigDecimal costo;
	private BigDecimal descue;
	private BigDecimal costoNeto;
	private BigDecimal utilidad;
	private BigDecimal precioSinImpuesto;
	private BigDecimal precioConImpuesto;

	private static final long serialVersionUID = 699586697147246L;

	public ProdComp() {
	}

	public ProdComp(String sucursal, String cedula, String proveedor, LocalDate fechaEmis, Integer numeroFact,
			BigDecimal cantidad, BigDecimal costo, BigDecimal descue, BigDecimal costoNeto, BigDecimal utilidad, BigDecimal precioSinImpuesto,
			BigDecimal precioConImpuesto) {

		this.sucursal = sucursal;
		this.cedula = cedula;
		this.proveedor = proveedor;
		this.fechaEmis = fechaEmis;
		this.numeroFact = numeroFact;
		this.cantidad = cantidad;
		this.costo = costo;
		this.descue = descue;
		this.costoNeto = costoNeto;
		this.utilidad = utilidad;
		this.precioSinImpuesto = precioSinImpuesto;
		this.precioConImpuesto = precioConImpuesto;
	}

	public String getCedula() {
		return cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	public String getProveedor() {
		return proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	public String getSucursal() {
		return sucursal;
	}

	public void setSucursal(String sucursal) {
		this.sucursal = sucursal;
	}


	public Integer getNumeroFact() {
		return numeroFact;
	}

	public void setNumeroFact(Integer numeroFact) {
		this.numeroFact = numeroFact;
	}

	public BigDecimal getCantidad() {
		return cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getCosto() {
		return costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	public BigDecimal getUtilidad() {
		return utilidad;
	}

	public void setUtilidad(BigDecimal utilidad) {
		this.utilidad = utilidad;
	}

	public BigDecimal getPrecioConImpuesto() {
		return precioConImpuesto;
	}

	public void setPrecioConImpuesto(BigDecimal precioConImpuesto) {
		this.precioConImpuesto = precioConImpuesto;
	}

	public BigDecimal getPrecioSinImpuesto() {
		return precioSinImpuesto;
	}

	public void setPrecioSinImpuesto(BigDecimal precioSinImpuesto) {
		this.precioSinImpuesto = precioSinImpuesto;
	}

	public BigDecimal getDescue() {
		return descue;
	}

	public void setDescue(BigDecimal descue) {
		this.descue = descue;
	}

	public BigDecimal getCostoNeto() {
		return costoNeto;
	}

	public void setCostoNeto(BigDecimal costoNeto) {
		this.costoNeto = costoNeto;
	}

	public LocalDate getFechaEmis() {
		return fechaEmis;
	}

	public void setFechaEmis(LocalDate fechaEmis) {
		this.fechaEmis = fechaEmis;
	}
}
