package ec.com.tecnointel.soem.inventario.modelo;
// Generated 16/09/2020 9:14:15 by Hibernate Tools 5.2.11.Final

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import ec.com.tecnointel.soem.parametro.modelo.Bodega;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * TomaFisi generated by hbm2java
 */
@Entity
@Table(name = "toma_fisi")
@NamedEntityGraph(name = "tomaFisi.Graph", attributeNodes = { 
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "bodega") })
public class TomaFisi implements java.io.Serializable {

	private Integer tomaFisiId;
	private Sucursal sucursal;
	private Bodega bodega;
	private LocalDate fechaRegi;
	private LocalDate fechaProc;
	private LocalDateTime fechaHoraRegi;
	private LocalDateTime fechaHoraProc;
	private Integer numero;
	private String refere;
	private String nota;
	private String estado;
	private Set<TomaFisiDeta> tomaFisiDetas = new HashSet<TomaFisiDeta>(0);

	private static final long serialVersionUID = 3015251656833304228L;

	public TomaFisi() {
	}

	@Id
	@TableGenerator(name = "idTomaFisi", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "toma_fisi", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTomaFisi")	
	@Column(name = "toma_fisi_id", unique = true, nullable = false)
	public Integer getTomaFisiId() {
		return tomaFisiId;
	}

	public void setTomaFisiId(Integer tomaFisiId) {
		this.tomaFisiId = tomaFisiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sucursal_id", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bodega_id", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@Column(columnDefinition = "DATE", name = "fecha_regi", nullable = false, length = 10)
	public LocalDate getFechaRegi() {
		return fechaRegi;
	}

	public void setFechaRegi(LocalDate fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "fecha_proc", nullable = false, length = 10)
	public LocalDate getFechaProc() {
		return fechaProc;
	}

	public void setFechaProc(LocalDate fechaProc) {
		this.fechaProc = fechaProc;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "fecha_hora_regi", nullable = false, length = 19)
	public LocalDateTime getFechaHoraRegi() {
		return fechaHoraRegi;
	}

	public void setFechaHoraRegi(LocalDateTime fechaHoraRegi) {
		this.fechaHoraRegi = fechaHoraRegi;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "fecha_hora_proc", nullable = false, length = 19)
	public LocalDateTime getFechaHoraProc() {
		return fechaHoraProc;
	}

	public void setFechaHoraProc(LocalDateTime fechaHoraProc) {
		this.fechaHoraProc = fechaHoraProc;
	}

	@Column(name = "numero", nullable = false, precision = 9, scale = 0)
	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "refere", nullable = true)
	public String getRefere() {
		return this.refere;
	}

	public void setRefere(String refere) {
		this.refere = refere;
	}

	@Column(name = "nota", nullable = true)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "estado", nullable = false, length = 30)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tomaFisi")
	public Set<TomaFisiDeta> getTomaFisiDetas() {
		return this.tomaFisiDetas;
	}

	public void setTomaFisiDetas(Set<TomaFisiDeta> tomaFisiDetas) {
		this.tomaFisiDetas = tomaFisiDetas;
	}
}
