package ec.com.tecnointel.soem.inventario.modelo;
// Generated 16/09/2020 9:14:15 by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * TomaFisiDeta generated by hbm2java
 */
@Entity
@Table(name = "toma_fisi_deta")
@NamedEntityGraph(name = "tomaFisiDeta.Graph", attributeNodes = { 
@NamedAttributeNode(value = "producto"), 
@NamedAttributeNode(value = "tomaFisi")})
public class TomaFisiDeta implements java.io.Serializable {

	private Integer tomaFisiDetaId;
	private TomaFisi tomaFisi;
	private Producto producto;
	private BigDecimal costoActu;
	private BigDecimal cantidActu;
	private BigDecimal costoCont;
	private BigDecimal cantidCont;

	private static final long serialVersionUID = -3848595773140150267L;

	public TomaFisiDeta() {
	}

	public TomaFisiDeta(Integer tomaFisiDetaId, TomaFisi tomaFisi, Producto producto, BigDecimal costoActu,
			BigDecimal cantidActu, BigDecimal costoCont, BigDecimal cantidCont) {
		this.tomaFisiDetaId = tomaFisiDetaId;
		this.tomaFisi = tomaFisi;
		this.producto = producto;
		this.costoActu = costoActu;
		this.cantidActu = cantidActu;
		this.costoCont = costoCont;
		this.cantidCont = cantidCont;
	}

	@Id
	@TableGenerator(name = "idTomaFisiDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "toma_fisi_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTomaFisiDeta")
	@Column(name = "toma_fisi_deta_id", unique = true, nullable = false)
	public Integer getTomaFisiDetaId() {
		return this.tomaFisiDetaId;
	}

	public void setTomaFisiDetaId(Integer tomaFisiDetaId) {
		this.tomaFisiDetaId = tomaFisiDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "toma_fisi_id", nullable = false)
	public TomaFisi getTomaFisi() {
		return this.tomaFisi;
	}

	public void setTomaFisi(TomaFisi tomaFisi) {
		this.tomaFisi = tomaFisi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_id", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "costo_actu", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoActu() {
		return this.costoActu;
	}

	public void setCostoActu(BigDecimal costoActu) {
		this.costoActu = costoActu;
	}

	@Column(name = "cantid_actu", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCantidActu() {
		return this.cantidActu;
	}

	public void setCantidActu(BigDecimal cantidActu) {
		this.cantidActu = cantidActu;
	}

	@Column(name = "costo_cont", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCostoCont() {
		return this.costoCont;
	}

	public void setCostoCont(BigDecimal costoCont) {
		this.costoCont = costoCont;
	}

	@Column(name = "cantid_cont", nullable = false, precision = 14, scale = 6)
	public BigDecimal getCantidCont() {
		return this.cantidCont;
	}

	public void setCantidCont(BigDecimal cantidCont) {
		this.cantidCont = cantidCont;
	}

}
