package ec.com.tecnointel.soem.caja.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;

import ec.com.tecnointel.soem.parametro.modelo.FormPago;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * CajaMoviFormPago generated by hbm2java
 */
@Entity
@Table(name = "caja_movi_form_pago")
@NamedEntityGraph(name = "cmfp.Graph", attributeNodes = { 
@NamedAttributeNode(value = "cajaMovi"),
@NamedAttributeNode(value = "formPago") })
public class CajaMoviFormPago implements java.io.Serializable {

	private Integer cmfpId;
	private CajaMovi cajaMovi;
	private FormPago formPago;
	private BigDecimal total;

	private static final long serialVersionUID = 4151756647971181417L;

	public CajaMoviFormPago() {
	}

	public CajaMoviFormPago(Integer cmfpId, CajaMovi cajaMovi, FormPago formPago, BigDecimal total) {
		this.cmfpId = cmfpId;
		this.cajaMovi = cajaMovi;
		this.formPago = formPago;
		this.total = total;
	}

	@Id
	@TableGenerator(name = "idCajaMoviFormPago", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "caja_movi_form_pago", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idCajaMoviFormPago")
	@Column(name = "CMFP_ID", unique = true, nullable = false)
	public Integer getCmfpId() {
		return this.cmfpId;
	}

	public void setCmfpId(Integer cmfpId) {
		this.cmfpId = cmfpId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAJA_MOVI_ID", nullable = false)
	public CajaMovi getCajaMovi() {
		return this.cajaMovi;
	}

	public void setCajaMovi(CajaMovi cajaMovi) {
		this.cajaMovi = cajaMovi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FORM_PAGO_ID", nullable = false)
	public FormPago getFormPago() {
		return this.formPago;
	}

	public void setFormPago(FormPago formPago) {
		this.formPago = formPago;
	}

	@Column(name = "TOTAL", nullable = false, precision = 14, scale = 6)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

}
