package ec.com.tecnointel.soem.caja.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import ec.com.tecnointel.soem.parametro.modelo.Persona;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;

/**
 * PersCaje generated by hbm2java
 */
@Entity
@Table(name = "pers_caje")
public class PersCaje implements java.io.Serializable {

	private Integer personaId;
	private Persona persona;
	private boolean estado;
	private Set<CajaMovi> cajaMovis = new HashSet<CajaMovi>(0);

	private static final long serialVersionUID = 8031152957856049610L;

	public PersCaje() {
	}

	public PersCaje(Persona persona, boolean estado) {
		this.persona = persona;
		this.estado = estado;
	}

	public PersCaje(Persona persona, boolean estado, Set<CajaMovi> cajaMovis) {
		this.persona = persona;
		this.estado = estado;
		this.cajaMovis = cajaMovis;
	}

	@Id
	@GenericGenerator(name = "idPersCaje", strategy = "foreign", parameters = @Parameter(name = "property", value = "persona"))
	@GeneratedValue(generator = "idPersCaje")
	// @TableGenerator(name = "idPersCaje", table = "Secuencial", pkColumnName =
	// "secuencial_id", pkColumnValue = "37", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator =
	// "idPersCaje")
	@Column(name = "PERSONA_ID", unique = true, nullable = false)
	public Integer getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(Integer personaId) {
		this.personaId = personaId;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@PrimaryKeyJoinColumn
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persCaje")
	public Set<CajaMovi> getCajaMovis() {
		return this.cajaMovis;
	}

	public void setCajaMovis(Set<CajaMovi> cajaMovis) {
		this.cajaMovis = cajaMovis;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((personaId == null) ? 0 : personaId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PersCaje other = (PersCaje) obj;
		if (personaId == null) {
			if (other.personaId != null)
				return false;
		} else if (!personaId.equals(other.personaId))
			return false;
		return true;
	}

}
