package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;

import ec.com.saolan.soem.asistencia.modelo.PersEmpl;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * AcciAuto generated by hbm2java
 */
@Entity
@Table(name = "acci_auto")
public class AcciPersAuto implements java.io.Serializable {

	private Integer acciPersAutoId;
	private AcciPers acciPers;
	private PersEmpl persEmpl;
	private Date fecha;
	private String estado;
	private Integer nivel;

	private static final long serialVersionUID = 464251827851702143L;

	public AcciPersAuto() {
	}

	public AcciPersAuto(Integer acciPersAutoId, AcciPers acciPers,
			PersEmpl persEmpl, Date fecha, String estado, Integer nivel) {
		this.acciPersAutoId = acciPersAutoId;
		this.acciPers = acciPers;
		this.persEmpl = persEmpl;
		this.fecha = fecha;
		this.estado = estado;
		this.nivel = nivel;
	}

	@Id
	@TableGenerator(name = "idAcciPersAuto", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "acci_pers_auto", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAcciPersAuto")
	@Column(name = "acci_auto_id", unique = true, nullable = false)
	public Integer getAcciPersAutoId() {
		return acciPersAutoId;
	}

	public void setAcciPersAutoId(Integer acciPersAutoId) {
		this.acciPersAutoId = acciPersAutoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acci_pers_id", nullable = false)
	public AcciPers getAcciPers() {
		return this.acciPers;
	}

	public void setAcciPers(AcciPers acciPers) {
		this.acciPers = acciPers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 29)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado", nullable = false, length = 4)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "nivel", nullable = false)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}
}
