package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * AcciPersTipo generated by hbm2java
 */
@Entity
@Table(name = "acci_pers_tipo")
public class AcciPersTipo implements java.io.Serializable {

	private Integer acciPersTipoId;
	private String descri;
	private String entradSali;
	private String estado;
	private Set<AcciPers> acciPerses = new HashSet<AcciPers>(0);

	private static final long serialVersionUID = 7815353809792773509L;

	public AcciPersTipo() {
	}

	public AcciPersTipo(Integer acciPersTipoId, String descri, String entradSali, String estado) {
		this.acciPersTipoId = acciPersTipoId;
		this.descri = descri;
		this.entradSali = entradSali;
		this.estado = estado;
	}

	public AcciPersTipo(Integer acciPersTipoId, String descri,
			String entradSali, Set<AcciPers> acciPerses) {
		this.acciPersTipoId = acciPersTipoId;
		this.descri = descri;
		this.entradSali = entradSali;
		this.acciPerses = acciPerses;
	}

	@Id
	@TableGenerator(name = "idAcciPersTipo", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "acci_pers_tipo", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAcciPersTipo")
	@Column(name = "acci_pers_tipo_id", unique = true, nullable = false)
	public Integer getAcciPersTipoId() {
		return this.acciPersTipoId;
	}

	public void setAcciPersTipoId(Integer acciPersTipoId) {
		this.acciPersTipoId = acciPersTipoId;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "entrad_sali", nullable = false, length = 32)
	public String getEntradSali() {
		return this.entradSali;
	}

	public void setEntradSali(String entradSali) {
		this.entradSali = entradSali;
	}

	@Column(name = "estado", nullable = false, length = 16)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acciPersTipo")
	public Set<AcciPers> getAcciPerses() {
		return this.acciPerses;
	}

	public void setAcciPerses(Set<AcciPers> acciPerses) {
		this.acciPerses = acciPerses;
	}
}
