package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import ec.com.saolan.soem.asistencia.modelo.PersEmpl;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * AcciPers generated by hbm2java
 */
@Entity
@Table(name = "acci_pers")
public class AcciPers implements java.io.Serializable {

	private Integer acciPersId;
	private AcciPersTipo acciPersTipo;
	private PersEmpl persEmpl;
	private Integer numero;
	private Date fechaRegi;
	private Date fechaEmis;
	private Date fechaRige;
	private String nota;
	private Integer usuarioId;
	private String estado;
	private Set<AcciPersProp> acciPersProps = new HashSet<AcciPersProp>(0);
	private Set<AcciPersActu> acciPersActus = new HashSet<AcciPersActu>(0);
	private Set<AcciPersAuto> acciAutos = new HashSet<AcciPersAuto>(0);

	private static final long serialVersionUID = -1159943497894799664L;

	public AcciPers() {
	}

	public AcciPers(Integer acciPersId, AcciPersTipo acciPersTipo,
			PersEmpl persEmpl, Integer numero, Date fechaRegi, Date fechaEmis,
			Date fechaRige, String estado) {
		this.acciPersId = acciPersId;
		this.acciPersTipo = acciPersTipo;
		this.persEmpl = persEmpl;
		this.numero = numero;
		this.fechaRegi = fechaRegi;
		this.fechaEmis = fechaEmis;
		this.fechaRige = fechaRige;
		this.estado = estado;
	}

	public AcciPers(Integer acciPersId, AcciPersTipo acciPersTipo,
			PersEmpl persEmpl, Integer numero, Date fechaRegi, Date fechaEmis,
			Date fechaRige, String nota, Integer usuarioId, String estado,
			Set<AcciPersProp> acciPersProps, Set<AcciPersActu> acciPersActus,
			Set<AcciPersAuto> acciAutos) {
		this.acciPersId = acciPersId;
		this.acciPersTipo = acciPersTipo;
		this.persEmpl = persEmpl;
		this.numero = numero;
		this.fechaRegi = fechaRegi;
		this.fechaEmis = fechaEmis;
		this.fechaRige = fechaRige;
		this.nota = nota;
		this.usuarioId = usuarioId;
		this.estado = estado;
		this.acciPersProps = acciPersProps;
		this.acciPersActus = acciPersActus;
		this.acciAutos = acciAutos;
	}

	@Id
	@TableGenerator(name = "idAcciPers", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "acci_pers", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAcciPers")
	@Column(name = "acci_pers_id", unique = true, nullable = false)
	public Integer getAcciPersId() {
		return this.acciPersId;
	}

	public void setAcciPersId(Integer acciPersId) {
		this.acciPersId = acciPersId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acci_pers_tipo_id", nullable = false)
	public AcciPersTipo getAcciPersTipo() {
		return this.acciPersTipo;
	}

	public void setAcciPersTipo(AcciPersTipo acciPersTipo) {
		this.acciPersTipo = acciPersTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Column(name = "numero", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_regi", nullable = false, length = 13)
	public Date getFechaRegi() {
		return this.fechaRegi;
	}

	public void setFechaRegi(Date fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_emis", nullable = false, length = 13)
	public Date getFechaEmis() {
		return this.fechaEmis;
	}

	public void setFechaEmis(Date fechaEmis) {
		this.fechaEmis = fechaEmis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_rige", nullable = false, length = 13)
	public Date getFechaRige() {
		return this.fechaRige;
	}

	public void setFechaRige(Date fechaRige) {
		this.fechaRige = fechaRige;
	}

	@Column(name = "nota", length = 1024)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "usuario_id")
	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acciPers")
	public Set<AcciPersProp> getAcciPersProps() {
		return this.acciPersProps;
	}

	public void setAcciPersProps(Set<AcciPersProp> acciPersProps) {
		this.acciPersProps = acciPersProps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acciPers")
	public Set<AcciPersActu> getAcciPersActus() {
		return this.acciPersActus;
	}

	public void setAcciPersActus(Set<AcciPersActu> acciPersActus) {
		this.acciPersActus = acciPersActus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acciPers")
	public Set<AcciPersAuto> getAcciAutos() {
		return this.acciAutos;
	}

	public void setAcciAutos(Set<AcciPersAuto> acciAutos) {
		this.acciAutos = acciAutos;
	}

}
