package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;

import ec.com.saolan.soem.asistencia.modelo.Cargo;
import ec.com.saolan.soem.asistencia.modelo.Departamento;
import ec.com.saolan.soem.asistencia.modelo.TipoCont;
import ec.com.tecnointel.soem.parametro.modelo.CentCost;
import ec.com.tecnointel.soem.parametro.modelo.Mapa;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * AcciPersProp generated by hbm2java
 */
@Entity
@Table(name = "acci_pers_prop")
public class AcciPersProp implements java.io.Serializable {

	private Integer acciPersPropId;
	private AcciPers acciPers;
	private Cargo cargo;
	private CentCost centCost;
	private Departamento departamento;
	private Mapa mapa;
	private TipoCont tipoCont;
	private BigDecimal sueldo;

	private static final long serialVersionUID = 1977629141401726124L;

	public AcciPersProp() {
	}

	public AcciPersProp(Integer acciPersPropId, AcciPers acciPers, Cargo cargo,
			CentCost centCost, Departamento departamento, Mapa mapa,
			TipoCont tipoCont, BigDecimal sueldo) {
		this.acciPersPropId = acciPersPropId;
		this.acciPers = acciPers;
		this.cargo = cargo;
		this.centCost = centCost;
		this.departamento = departamento;
		this.mapa = mapa;
		this.tipoCont = tipoCont;
		this.sueldo = sueldo;
	}

	@Id
	@TableGenerator(name = "idAcciPersProp", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "acci_pers_prop", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAcciPersProp")
	@Column(name = "acci_pers_prop_id", unique = true, nullable = false)
	public Integer getAcciPersPropId() {
		return this.acciPersPropId;
	}

	public void setAcciPersPropId(Integer acciPersPropId) {
		this.acciPersPropId = acciPersPropId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acci_pers_id", nullable = false)
	public AcciPers getAcciPers() {
		return this.acciPers;
	}

	public void setAcciPers(AcciPers acciPers) {
		this.acciPers = acciPers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cargo_id", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cent_cost_id", nullable = false)
	public CentCost getCentCost() {
		return this.centCost;
	}

	public void setCentCost(CentCost centCost) {
		this.centCost = centCost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento_id", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mapa_id", nullable = false)
	public Mapa getMapa() {
		return this.mapa;
	}

	public void setMapa(Mapa mapa) {
		this.mapa = mapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_cont_id", nullable = false)
	public TipoCont getTipoCont() {
		return this.tipoCont;
	}

	public void setTipoCont(TipoCont tipoCont) {
		this.tipoCont = tipoCont;
	}

	@Column(name = "sueldo", nullable = false, precision = 8)
	public BigDecimal getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(BigDecimal sueldo) {
		this.sueldo = sueldo;
	}

}
