package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import ec.com.saolan.soem.asistencia.modelo.PersEmpl;
import ec.com.tecnointel.soem.contabilidad.modelo.Transaccion;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Nomina generated by hbm2java
 */
@Entity
@Table(name = "nomina")
public class Nomina implements java.io.Serializable {

	private Integer nominaId;
	private PersEmpl persEmpl;
	private Transaccion transaccion;
	private String anio;
	private String mes;
	private Date fechaRegi;
	private BigDecimal sueldoBase;
	private BigDecimal diasTrab;
	private BigDecimal diasEnfe;
	private BigDecimal diasMate;
	private BigDecimal sueldo;
	private String estado;
	private Set<NomiDeta> nomiMovis = new HashSet<NomiDeta>(0);

	private static final long serialVersionUID = -6953079489813063386L;

	public Nomina() {
	}

	public Nomina(Integer nominaId, PersEmpl persEmpl, String anio, String mes,
			Date fechaRegi, BigDecimal sueldoBase, BigDecimal diasTrab,
			BigDecimal diasEnfe, BigDecimal diasMate, BigDecimal sueldo,
			String estado) {
		this.nominaId = nominaId;
		this.persEmpl = persEmpl;
		this.anio = anio;
		this.mes = mes;
		this.fechaRegi = fechaRegi;
		this.sueldoBase = sueldoBase;
		this.diasTrab = diasTrab;
		this.diasEnfe = diasEnfe;
		this.diasMate = diasMate;
		this.sueldo = sueldo;
		this.estado = estado;
	}

	public Nomina(Integer nominaId, PersEmpl persEmpl, Transaccion transaccion,
			String anio, String mes, Date fechaRegi, BigDecimal sueldoBase,
			BigDecimal diasTrab, BigDecimal diasEnfe, BigDecimal diasMate,
			BigDecimal sueldo, String estado, Set<NomiDeta> nomiMovis) {
		this.nominaId = nominaId;
		this.persEmpl = persEmpl;
		this.transaccion = transaccion;
		this.anio = anio;
		this.mes = mes;
		this.fechaRegi = fechaRegi;
		this.sueldoBase = sueldoBase;
		this.diasTrab = diasTrab;
		this.diasEnfe = diasEnfe;
		this.diasMate = diasMate;
		this.sueldo = sueldo;
		this.estado = estado;
		this.nomiMovis = nomiMovis;
	}

	@Id
	@TableGenerator(name = "idNomina", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "nomina", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idNomina")
	@Column(name = "nomina_id", unique = true, nullable = false)
	public Integer getNominaId() {
		return this.nominaId;
	}

	public void setNominaId(Integer nominaId) {
		this.nominaId = nominaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaccion_id")
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@Column(name = "anio", nullable = false, length = 4)
	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	@Column(name = "mes", nullable = false, length = 2)
	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_regi", nullable = false, length = 13)
	public Date getFechaRegi() {
		return this.fechaRegi;
	}

	public void setFechaRegi(Date fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Column(name = "sueldo_base", nullable = false, precision = 10)
	public BigDecimal getSueldoBase() {
		return this.sueldoBase;
	}

	public void setSueldoBase(BigDecimal sueldoBase) {
		this.sueldoBase = sueldoBase;
	}

	@Column(name = "dias_trab", nullable = false, precision = 10)
	public BigDecimal getDiasTrab() {
		return this.diasTrab;
	}

	public void setDiasTrab(BigDecimal diasTrab) {
		this.diasTrab = diasTrab;
	}

	@Column(name = "dias_enfe", nullable = false, precision = 6)
	public BigDecimal getDiasEnfe() {
		return this.diasEnfe;
	}

	public void setDiasEnfe(BigDecimal diasEnfe) {
		this.diasEnfe = diasEnfe;
	}

	@Column(name = "dias_mate", nullable = false, precision = 6)
	public BigDecimal getDiasMate() {
		return this.diasMate;
	}

	public void setDiasMate(BigDecimal diasMate) {
		this.diasMate = diasMate;
	}

	@Column(name = "sueldo", nullable = false, precision = 10)
	public BigDecimal getSueldo() {
		return this.sueldo;
	}

	public void setSueldo(BigDecimal sueldo) {
		this.sueldo = sueldo;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomina")
	public Set<NomiDeta> getNomiMovis() {
		return this.nomiMovis;
	}

	public void setNomiMovis(Set<NomiDeta> nomiMovis) {
		this.nomiMovis = nomiMovis;
	}

}
