package ec.com.saolan.soem.nomina.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.Date;

import ec.com.saolan.soem.asistencia.modelo.PersEmpl;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * NomiMovi generated by hbm2java
 */
@Entity
@Table(name = "nomi_deta")
public class NomiDeta implements java.io.Serializable {

	private Integer nomiDetaId;
	private DocuNomi docuNomi;
	private Nomina nomina;
	private PersEmpl persEmpl;
	private Date fecha;
	private BigDecimal valor;
	private String estado;
	private String nota;

	private static final long serialVersionUID = -5954895375486200633L;

	public NomiDeta() {
	}

	public NomiDeta(Integer nomiDetaId, DocuNomi docuNomi, PersEmpl persEmpl, Date fecha, BigDecimal valor,
			String nota) {
		this.nomiDetaId = nomiDetaId;
		this.docuNomi = docuNomi;
		this.persEmpl = persEmpl;
		this.fecha = fecha;
		this.valor = valor;
		this.nota = nota;
	}

	public NomiDeta(Integer nomiDetaId, DocuNomi docuNomi, Nomina nomina, PersEmpl persEmpl, Date fecha,
			BigDecimal valor, String nota) {
		this.nomiDetaId = nomiDetaId;
		this.docuNomi = docuNomi;
		this.nomina = nomina;
		this.persEmpl = persEmpl;
		this.fecha = fecha;
		this.valor = valor;
		this.nota = nota;
	}

	@Id
	@TableGenerator(name = "idNomiDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "nomi_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idNomiDeta")
	@Column(name = "nomi_deta_id", unique = true, nullable = false)
	public Integer getNomiDetaId() {
		return nomiDetaId;
	}

	public void setNomiDetaId(Integer nomiDetaId) {
		this.nomiDetaId = nomiDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documento_id", nullable = false)
	public DocuNomi getDocuNomi() {
		return this.docuNomi;
	}

	public void setDocuNomi(DocuNomi docuNomi) {
		this.docuNomi = docuNomi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nomina_id")
	public Nomina getNomina() {
		return this.nomina;
	}

	public void setNomina(Nomina nomina) {
		this.nomina = nomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "valor", nullable = false, precision = 10)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "nota", nullable = false)
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
}
