package ec.com.tecnointel.soem.ingreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProvGrup generated by hbm2java
 */
@Entity
@Table(name = "prov_grup")
public class ProvGrup implements java.io.Serializable {

	private Integer provGrupId;
	private String descri;
	private String nota;
	private boolean estado;
	private Set<ProvGrupPlanCuen> provGrupPlanCuens = new HashSet<ProvGrupPlanCuen>(0);
	private Set<PersProv> persProvs = new HashSet<PersProv>(0);

	private static final long serialVersionUID = 479349985223860965L;

	public ProvGrup() {
	}

	public ProvGrup(Integer provGrupId, String descri, boolean estado) {
		this.provGrupId = provGrupId;
		this.descri = descri;
		this.estado = estado;
	}

	public ProvGrup(Integer provGrupId, String descri, String nota, boolean estado,
			Set<ProvGrupPlanCuen> provGrupPlanCuens, Set<PersProv> persProvs) {
		this.provGrupId = provGrupId;
		this.descri = descri;
		this.nota = nota;
		this.estado = estado;
		this.provGrupPlanCuens = provGrupPlanCuens;
		this.persProvs = persProvs;
	}

	@Id
	@TableGenerator(name = "idProvGrup", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prov_grup", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProvGrup")
	@Column(name = "PROV_GRUP_ID", unique = true, nullable = false)
	public Integer getProvGrupId() {
		return this.provGrupId;
	}

	public void setProvGrupId(Integer provGrupId) {
		this.provGrupId = provGrupId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provGrup")
	public Set<ProvGrupPlanCuen> getProvGrupPlanCuens() {
		return this.provGrupPlanCuens;
	}

	public void setProvGrupPlanCuens(Set<ProvGrupPlanCuen> provGrupPlanCuens) {
		this.provGrupPlanCuens = provGrupPlanCuens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provGrup")
	public Set<PersProv> getPersProvs() {
		return this.persProvs;
	}

	public void setPersProvs(Set<PersProv> persProvs) {
		this.persProvs = persProvs;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((provGrupId == null) ? 0 : provGrupId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProvGrup other = (ProvGrup) obj;
		if (provGrupId == null) {
			if (other.provGrupId != null)
				return false;
		} else if (!provGrupId.equals(other.provGrupId))
			return false;
		return true;
	}

}
