package ec.com.tecnointel.soem.ingreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.contabilidad.modelo.PlanCuen;
import ec.com.tecnointel.soem.parametro.modelo.Documento;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ProvGrupPlanCuen generated by hbm2java
 */
@Entity
@Table(name = "prov_grup_plan_cuen")
@NamedEntityGraph(name = "pgpc.Graph", attributeNodes = {
@NamedAttributeNode(value = "provGrup"),
@NamedAttributeNode(value = "planCuen"),
@NamedAttributeNode(value = "documento"),})
public class ProvGrupPlanCuen implements java.io.Serializable {

	private Integer pgpcId;
	private PlanCuen planCuen;
	private ProvGrup provGrup;
	private Documento documento;
	private String tipoTran;
	
	private static final long serialVersionUID = 2408215536044622470L;

	public ProvGrupPlanCuen() {
	}

	public ProvGrupPlanCuen(Integer pgpcId, PlanCuen planCuen, ProvGrup provGrup, String tipoTran) {
		this.pgpcId = pgpcId;
		this.planCuen = planCuen;
		this.provGrup = provGrup;
		this.tipoTran = tipoTran;
	}

	@Id
	@TableGenerator(name = "idProvGrupPlanCuen", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "prov_grup_plan_cuen", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idProvGrupPlanCuen")
	@Column(name = "PGPC_ID", unique = true, nullable = false)
	public Integer getPgpcId() {
		return this.pgpcId;
	}

	public void setPgpcId(Integer pgpcId) {
		this.pgpcId = pgpcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROV_GRUP_ID", nullable = false)
	public ProvGrup getProvGrup() {
		return this.provGrup;
	}

	public void setProvGrup(ProvGrup provGrup) {
		this.provGrup = provGrup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENTO_ID", nullable = false)
	public Documento getDocumento() {
		return documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "TIPO_TRAN")
	public String getTipoTran() {
		return tipoTran;
	}

	public void setTipoTran(String tipoTran) {
		this.tipoTran = tipoTran;
	}
	
}
