package ec.com.tecnointel.soem.ingreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.NamedSubgraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Retencion generated by hbm2java
 */
@Entity
@Table(name = "retencion")
@NamedEntityGraph(name = "retencion.Graph", attributeNodes = {
	@NamedAttributeNode(value = "ingreso", subgraph = "persProv.Graph"),
},
subgraphs = {
		@NamedSubgraph(name = "persProv.Graph",attributeNodes =
			{ 
				@NamedAttributeNode(value = "persProv"),
				@NamedAttributeNode(value = "sucursal"),
				@NamedAttributeNode(value = "docuIngr")
			}) 
		}
)
public class Retencion implements java.io.Serializable {

	private Integer retencionId;
	private Ingreso ingreso;
	private boolean documeElec;
	private LocalDate fechaRegi;
	private LocalDate fechaEmis;
	private LocalDateTime fechaAuto;
	private LocalDateTime fechaHoraRegi;
	private LocalDateTime fechaHoraEmis;
	private String serie1;
	private String serie2;
	private Integer numero;
	private String autori;
	private String claveAcce;
	private String nota;
	private String estado;
	private String estadoDocuElec;
	private String motivoRech;
	private String leyen1;
	private String leyen2;
	private String msgInfoAdic;
	
	private Set<ReteDeta> reteDetas = new HashSet<ReteDeta>(0);

	private static final long serialVersionUID = 8346838988889150754L;

	public Retencion() {
	}

	@Id
	@TableGenerator(name = "idRetencion", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "retencion", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRetencion")
	@Column(name = "RETENCION_ID", unique = true, nullable = false)
	public Integer getRetencionId() {
		return this.retencionId;
	}

	public void setRetencionId(Integer retencionId) {
		this.retencionId = retencionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "INGRESO_ID", nullable = true)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@Column(name = "DOCUME_ELEC", nullable = false)
	public boolean isDocumeElec() {
		return this.documeElec;
	}

	public void setDocumeElec(boolean documeElec) {
		this.documeElec = documeElec;
	}

	@Column(columnDefinition = "DATE", name = "FECHA_REGI", nullable = false, length = 10)
	public LocalDate getFechaRegi() {
		return fechaRegi;
	}

	public void setFechaRegi(LocalDate fechaRegi) {
		this.fechaRegi = fechaRegi;
	}

	@Column(columnDefinition = "DATE", name = "FECHA_EMIS", nullable = false, length = 10)
	public LocalDate getFechaEmis() {
		return fechaEmis;
	}

	public void setFechaEmis(LocalDate fechaEmis) {
		this.fechaEmis = fechaEmis;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "FECHA_HORA_REGI", nullable = false, length = 19)
	public LocalDateTime getFechaHoraRegi() {
		return fechaHoraRegi;
	}

	public void setFechaHoraRegi(LocalDateTime fechaHoraRegi) {
		this.fechaHoraRegi = fechaHoraRegi;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "FECHA_HORA_EMIS", nullable = false, length = 19)
	public LocalDateTime getFechaHoraEmis() {
		return fechaHoraEmis;
	}

	public void setFechaHoraEmis(LocalDateTime fechaHoraEmis) {
		this.fechaHoraEmis = fechaHoraEmis;
	}
	
	@Column(columnDefinition = "TIMESTAMP", name = "FECHA_AUTO", nullable = false, length = 19)
	public LocalDateTime getFechaAuto() {
		return fechaAuto;
	}

	public void setFechaAuto(LocalDateTime fechaAuto) {
		this.fechaAuto = fechaAuto;
	}

	@Column(name = "SERIE1", nullable = false, length = 3)
	public String getSerie1() {
		return this.serie1;
	}

	public void setSerie1(String serie1) {
		this.serie1 = serie1;
	}

	@Column(name = "SERIE2", nullable = false, length = 3)
	public String getSerie2() {
		return this.serie2;
	}

	public void setSerie2(String serie2) {
		this.serie2 = serie2;
	}

	@Column(name = "NUMERO", nullable = false, precision = 10, scale = 0)
	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "AUTORI", nullable = false, length = 60)
	public String getAutori() {
		return this.autori;
	}

	public void setAutori(String autori) {
		this.autori = autori;
	}

	@Column(name = "CLAVE_ACCE", nullable = false, length = 60)
	public String getClaveAcce() {
		return this.claveAcce;
	}

	public void setClaveAcce(String claveAcce) {
		this.claveAcce = claveAcce;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "ESTADO", nullable = false)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "ESTADO_DOCU_ELEC", nullable = false)
	public String getEstadoDocuElec() {
		return estadoDocuElec;
	}

	public void setEstadoDocuElec(String estadoDocuElec) {
		this.estadoDocuElec = estadoDocuElec;
	}

	@Column(name = "MOTIVO_RECH")
	public String getMotivoRech() {
		return motivoRech;
	}

	public void setMotivoRech(String motivoRech) {
		this.motivoRech = motivoRech;
	}

	@Column(name = "LEYEN1")
	public String getLeyen1() {
		return leyen1;
	}

	public void setLeyen1(String leyen1) {
		this.leyen1 = leyen1;
	}

	@Column(name = "LEYEN2")
	public String getLeyen2() {
		return leyen2;
	}

	public void setLeyen2(String leyen2) {
		this.leyen2 = leyen2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retencion", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
	public Set<ReteDeta> getReteDetas() {
		return this.reteDetas;
	}

	public void setReteDetas(Set<ReteDeta> reteDetas) {
		this.reteDetas = reteDetas;
	}

	@Column(name = "MSG_INFO_ADIC")
	public String getMsgInfoAdic() {
		return msgInfoAdic;
	}

	public void setMsgInfoAdic(String msgInfoAdic) {
		this.msgInfoAdic = msgInfoAdic;
	}
}
