package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * MenuNive generated by hbm2java
 */
@Entity
@Table(name = "menu_nive")
public class MenuNive implements java.io.Serializable {

	private Integer menuNiveId;
	private String descri;
	private Integer nivel;
	private Set<Menu> menus = new HashSet<Menu>(0);

	private static final long serialVersionUID = -7420310847569852907L;

	public MenuNive() {
	}

	public MenuNive(Integer menuNiveId, String descri, Integer nivel) {
		this.menuNiveId = menuNiveId;
		this.descri = descri;
		this.nivel = nivel;
	}

	public MenuNive(Integer menuNiveId, String descri, Integer nivel, Set<Menu> menus) {
		this.menuNiveId = menuNiveId;
		this.descri = descri;
		this.nivel = nivel;
		this.menus = menus;
	}

	@Id
	@TableGenerator(name = "idMenuNive", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "menu_nive", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idMenuNive")
	@Column(name = "MENU_NIVE_ID", unique = true, nullable = false)
	public Integer getMenuNiveId() {
		return this.menuNiveId;
	}

	public void setMenuNiveId(Integer menuNiveId) {
		this.menuNiveId = menuNiveId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "NIVEL", nullable = false)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuNive")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((menuNiveId == null) ? 0 : menuNiveId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MenuNive other = (MenuNive) obj;
		if (menuNiveId == null) {
			if (other.menuNiveId != null)
				return false;
		} else if (!menuNiveId.equals(other.menuNiveId))
			return false;
		return true;
	}

}
