package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu")
@NamedEntityGraph(name = "menu.Graph", 
attributeNodes = {
@NamedAttributeNode(value = "menu"),
@NamedAttributeNode(value = "menuNive") })
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private Menu menu;
	private MenuNive menuNive;
	private String descri;
	private String paginaRuta;
	private boolean detall;
	private boolean estado;
	private Set<RolMenu> rolMenus = new HashSet<RolMenu>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);

	private static final long serialVersionUID = 1550712307696890499L;

	public Menu() {
	}

	public Menu(Integer menuId, MenuNive menuNive, String descri, boolean detall, boolean estado) {
		this.menuId = menuId;
		this.menuNive = menuNive;
		this.descri = descri;
		this.detall = detall;
		this.estado = estado;
	}

	public Menu(Integer menuId, Menu menu, MenuNive menuNive, String descri, String paginaRuta, boolean detall,
			boolean estado, Set<RolMenu> rolMenus, Set<Menu> menus) {
		this.menuId = menuId;
		this.menu = menu;
		this.menuNive = menuNive;
		this.descri = descri;
		this.paginaRuta = paginaRuta;
		this.detall = detall;
		this.estado = estado;
		this.rolMenus = rolMenus;
		this.menus = menus;
	}

	@Id
//	@TableGenerator(name = "idMenu", table = "Secuencial", pkColumnName = "secuencial_id", pkColumnValue = "31", valueColumnName = "numero", allocationSize = 1)
//	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idMenu")
	@Column(name = "MENU_ID", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_SUPE_ID")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENU_NIVE_ID", nullable = false)
	public MenuNive getMenuNive() {
		return this.menuNive;
	}

	public void setMenuNive(MenuNive menuNive) {
		this.menuNive = menuNive;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "PAGINA_RUTA")
	public String getPaginaRuta() {
		return this.paginaRuta;
	}

	public void setPaginaRuta(String paginaRuta) {
		this.paginaRuta = paginaRuta;
	}

	@Column(name = "DETALL", nullable = false)
	public boolean isDetall() {
		return this.detall;
	}

	public void setDetall(boolean detall) {
		this.detall = detall;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<RolMenu> getRolMenus() {
		return this.rolMenus;
	}

	public void setRolMenus(Set<RolMenu> rolMenus) {
		this.rolMenus = rolMenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((descri == null) ? 0 : descri.hashCode());
		result = prime * result + ((menuId == null) ? 0 : menuId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Menu other = (Menu) obj;
		if (descri == null) {
			if (other.descri != null)
				return false;
		} else if (!descri.equals(other.descri))
			return false;
		if (menuId == null) {
			if (other.menuId != null)
				return false;
		} else if (!menuId.equals(other.menuId))
			return false;
		return true;
	}

}
