package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol")
// @NamedEntityGraph(name = "rol.Graph",
// attributeNodes = {
// @NamedAttributeNode(value = "rolMenus"),
// @NamedAttributeNode(value = "rolPerms"),
// @NamedAttributeNode(value = "rolPrecs"),
// @NamedAttributeNode(value = "rolSucus"),
// @NamedAttributeNode(value = "rolFormPagos"),
// @NamedAttributeNode(value = "rolBodes"),
// @NamedAttributeNode(value = "rolDocus")
// })
public class Rol implements java.io.Serializable {

	private Integer rolId;
	private String descri;
	private boolean estado;
	private Set<RolPersUsua> rolPersUsuas = new HashSet<RolPersUsua>(0);
	private Set<RolMenu> rolMenus = new HashSet<RolMenu>(0);
	private Set<RolPerm> rolPerms = new HashSet<RolPerm>(0);
	private Set<RolPrec> rolPrecs = new HashSet<RolPrec>(0);
	private Set<RolSucu> rolSucus = new HashSet<RolSucu>(0);
	private Set<RolFormPago> rolFormPagos = new HashSet<RolFormPago>(0);
	private Set<RolBode> rolBodes = new HashSet<RolBode>(0);
	private Set<RolDocu> rolDocus = new HashSet<RolDocu>(0);

	private static final long serialVersionUID = -8026582634950456660L;

	public Rol() {
	}

	public Rol(Integer rolId, String descri, boolean estado) {
		this.rolId = rolId;
		this.descri = descri;
		this.estado = estado;
	}

	public Rol(Integer rolId, String descri, boolean estado, Set<RolPersUsua> rolPersUsuas, Set<RolMenu> rolMenus,
			Set<RolPerm> rolPerms, Set<RolPrec> rolPrecs, Set<RolSucu> rolSucus, Set<RolFormPago> rolFormPagos,
			Set<RolBode> rolBodes, Set<RolDocu> rolDocus) {
		this.rolId = rolId;
		this.descri = descri;
		this.estado = estado;
		this.rolPersUsuas = rolPersUsuas;
		this.rolMenus = rolMenus;
		this.rolPerms = rolPerms;
		this.rolPrecs = rolPrecs;
		this.rolSucus = rolSucus;
		this.rolFormPagos = rolFormPagos;
		this.rolBodes = rolBodes;
		this.rolDocus = rolDocus;
	}

	@Id
	@TableGenerator(name = "idRol", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "rol", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRol")
	@Column(name = "ROL_ID", unique = true, nullable = false)
	public Integer getRolId() {
		return this.rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolPersUsua> getRolPersUsuas() {
		return this.rolPersUsuas;
	}

	public void setRolPersUsuas(Set<RolPersUsua> rolPersUsuas) {
		this.rolPersUsuas = rolPersUsuas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolMenu> getRolMenus() {
		return this.rolMenus;
	}

	public void setRolMenus(Set<RolMenu> rolMenus) {
		this.rolMenus = rolMenus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolPerm> getRolPerms() {
		return this.rolPerms;
	}

	public void setRolPerms(Set<RolPerm> rolPerms) {
		this.rolPerms = rolPerms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolPrec> getRolPrecs() {
		return this.rolPrecs;
	}

	public void setRolPrecs(Set<RolPrec> rolPrecs) {
		this.rolPrecs = rolPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolSucu> getRolSucus() {
		return this.rolSucus;
	}

	public void setRolSucus(Set<RolSucu> rolSucus) {
		this.rolSucus = rolSucus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolFormPago> getRolFormPagos() {
		return this.rolFormPagos;
	}

	public void setRolFormPagos(Set<RolFormPago> rolFormPagos) {
		this.rolFormPagos = rolFormPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolBode> getRolBodes() {
		return this.rolBodes;
	}

	public void setRolBodes(Set<RolBode> rolBodes) {
		this.rolBodes = rolBodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolDocu> getRolDocus() {
		return this.rolDocus;
	}

	public void setRolDocus(Set<RolDocu> rolDocus) {
		this.rolDocus = rolDocus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rolId == null) ? 0 : rolId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Rol other = (Rol) obj;
		if (rolId == null) {
			if (other.rolId != null)
				return false;
		} else if (!rolId.equals(other.rolId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return String.format("%s[rolId=%d]", getClass().getSimpleName(), getRolId());
	}

}
