package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.parametro.modelo.Bodega;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * RolBode generated by hbm2java
 */
@Entity
@Table(name = "rol_bode")
@NamedEntityGraph(name = "rolBode.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "rol"), 
@NamedAttributeNode(value = "bodega") })
public class RolBode implements java.io.Serializable {

	private Integer rolBodeId;
	private Bodega bodega;
	private Rol rol;
	private Sucursal sucursal;
	private Boolean predet;
	private Boolean acceso;

	private static final long serialVersionUID = -5933143339898550327L;

	public RolBode() {
	}

	public RolBode(Integer rolBodeId, Bodega bodega, Rol rol, Sucursal sucursal, Boolean predet, Boolean acceso) {
		this.rolBodeId = rolBodeId;
		this.bodega = bodega;
		this.rol = rol;
		this.sucursal = sucursal;
		this.predet = predet;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idRolBode", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "rol_bode", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRolBode")
	@Column(name = "ROL_BODE_ID", unique = true, nullable = false)
	public Integer getRolBodeId() {
		return this.rolBodeId;
	}

	public void setRolBodeId(Integer rolBodeId) {
		this.rolBodeId = rolBodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BODEGA_ID", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "PREDET", nullable = false)
	public Boolean getPredet() {
		return predet;
	}

	public void setPredet(Boolean predet) {
		this.predet = predet;
	}

	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

}
