package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.parametro.modelo.Precio;
import ec.com.tecnointel.soem.parametro.modelo.Sucursal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * RolPrec generated by hbm2java
 */
@Entity
@Table(name = "rol_prec")
@NamedEntityGraph(name = "rolPrec.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "rol"), 
@NamedAttributeNode(value = "precio") })
public class RolPrec implements java.io.Serializable {

	private Integer rolPrecId;
	private Precio precio;
	private Rol rol;
	private Sucursal sucursal;
	private Boolean predet;
	private Boolean acceso;

	private static final long serialVersionUID = -6794363435030504362L;

	public RolPrec() {
	}

	public RolPrec(Precio precio, Rol rol, Sucursal sucursal, Boolean predet, Boolean acceso) {
		this.precio = precio;
		this.rol = rol;
		this.sucursal = sucursal;
		this.predet = predet;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idRolPrec", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "rol_prec", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRolPrec")
	@Column(name = "ROL_PREC_ID", unique = true, nullable = false)
	public Integer getRolPrecId() {
		return this.rolPrecId;
	}

	public void setRolPrecId(Integer rolPrecId) {
		this.rolPrecId = rolPrecId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRECIO_ID", nullable = false)
	public Precio getPrecio() {
		return this.precio;
	}

	public void setPrecio(Precio precio) {
		this.precio = precio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "PREDET", nullable = false)
	public Boolean getPredet() {
		return predet;
	}

	public void setPredet(Boolean predet) {
		this.predet = predet;
	}

	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((precio == null) ? 0 : precio.hashCode());
		result = prime * result + ((rol == null) ? 0 : rol.hashCode());
		result = prime * result + ((sucursal == null) ? 0 : sucursal.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RolPrec other = (RolPrec) obj;
		if (precio == null) {
			if (other.precio != null)
				return false;
		} else if (!precio.equals(other.precio))
			return false;
		if (rol == null) {
			if (other.rol != null)
				return false;
		} else if (!rol.equals(other.rol))
			return false;
		if (sucursal == null) {
			if (other.sucursal != null)
				return false;
		} else if (!sucursal.equals(other.sucursal))
			return false;
		return true;
	}

}
