package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * RolPersUsua generated by hbm2java
 */
@Entity
@Table(name = "rol_pers_usua")
@NamedEntityGraph(name = "rolPersUsua.Graph", attributeNodes = {
@NamedAttributeNode(value = "persUsua"),
@NamedAttributeNode(value = "rol") })
public class RolPersUsua implements java.io.Serializable {

	private Integer rolPersUsuaId;
	private PersUsua persUsua;
	private Rol rol;

	private static final long serialVersionUID = 350306571707977237L;

	public RolPersUsua() {
	}

	public RolPersUsua(Integer rolPersUsuaId, PersUsua persUsua, Rol rol) {
		this.rolPersUsuaId = rolPersUsuaId;
		this.persUsua = persUsua;
		this.rol = rol;
	}

	@Id
	@TableGenerator(name = "idRolPersUsua", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "rol_pers_usua", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idRolPersUsua")
	@Column(name = "ROL_PERS_USUA_ID", unique = true, nullable = false)
	public Integer getRolPersUsuaId() {
		return this.rolPersUsuaId;
	}

	public void setRolPersUsuaId(Integer rolPersUsuaId) {
		this.rolPersUsuaId = rolPersUsuaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONA_ID", nullable = false)
	public PersUsua getPersUsua() {
		return this.persUsua;
	}

	public void setPersUsua(PersUsua persUsua) {
		this.persUsua = persUsua;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
