package ec.com.tecnointel.soem.seguridad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Secuencial generated by hbm2java
 */
@Entity
@Table(name = "secuencial")
public class Secuencial implements java.io.Serializable {

	private Integer secuencialId;
	private String tabla;
	private Integer numero;
	private Set<Auditoria> auditorias = new HashSet<Auditoria>(0);

	private static final long serialVersionUID = 1170450416173941260L;

	public Secuencial() {
	}

	public Secuencial(Integer secuencialId, String tabla, Integer numero) {
		this.secuencialId = secuencialId;
		this.tabla = tabla;
		this.numero = numero;
	}

	public Secuencial(Integer secuencialId, String tabla, Integer numero, Set<Auditoria> auditorias) {
		this.secuencialId = secuencialId;
		this.tabla = tabla;
		this.numero = numero;
		this.auditorias = auditorias;
	}

	@Id
	// @TableGenerator(name = "idSecuencial", table = "Secuencial", pkColumnName
	// = "secuencial_id", pkColumnValue = "70", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator =
	// "idSecuencial")
	@Column(name = "SECUENCIAL_ID", unique = true, nullable = false)
	public Integer getSecuencialId() {
		return this.secuencialId;
	}

	public void setSecuencialId(Integer secuencialId) {
		this.secuencialId = secuencialId;
	}

	@Column(name = "TABLA", nullable = false, length = 100)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "NUMERO", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secuencial")
	public Set<Auditoria> getAuditorias() {
		return this.auditorias;
	}

	public void setAuditorias(Set<Auditoria> auditorias) {
		this.auditorias = auditorias;
	}

}
