package ec.com.tecnointel.soem.contabilidad.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * TranDeta generated by hbm2java
 */
@Entity
@Table(name = "tran_deta")
@NamedEntityGraph(name = "tranDeta.Graph", attributeNodes = {
		@NamedAttributeNode(value = "planCuen")
})
public class TranDeta implements java.io.Serializable {

	private Integer tranDetaId;
	private PlanCuen planCuen;
	private Transaccion transaccion;
	private LocalDate fechaEmis;
	private LocalDateTime fechaHoraEmis;
	private BigDecimal total;
	private String nota;

	private static final long serialVersionUID = 5407034900789938509L;

	public TranDeta() {
	}

	@Id
	@TableGenerator(name = "idTranDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "tran_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTranDeta")
	@Column(name = "TRAN_DETA_ID", unique = true, nullable = false)
	public Integer getTranDetaId() {
		return this.tranDetaId;
	}

	public void setTranDetaId(Integer tranDetaId) {
		this.tranDetaId = tranDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACCION_ID", nullable = false)
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@Column(columnDefinition = "DATE", name = "FECHA_EMIS", nullable = false, length = 10)
	public LocalDate getFechaEmis() {
		return fechaEmis;
	}

	public void setFechaEmis(LocalDate fechaEmis) {
		this.fechaEmis = fechaEmis;
	}

	@Column(columnDefinition = "TIMESTAMP", name = "FECHA_HORA_EMIS", nullable = false, length = 19)
	public LocalDateTime getFechaHoraEmis() {
		return fechaHoraEmis;
	}

	public void setFechaHoraEmis(LocalDateTime fechaHoraEmis) {
		this.fechaHoraEmis = fechaHoraEmis;
	}

	@Column(name = "TOTAL", nullable = false, precision = 14, scale = 6)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}
}
