package ec.com.tecnointel.soem.parametro.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import ec.com.saolan.soem.nomina.modelo.AcciPersActu;
import ec.com.saolan.soem.nomina.modelo.AcciPersProp;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * CentCost generated by hbm2java
 */
@Entity
@Table(name = "cent_cost")
public class CentCost implements java.io.Serializable {

	private int centCostId;
	private String codigo;
	private String descri;
	private String estado;
	private Set<AcciPersActu> acciPersActus = new HashSet<AcciPersActu>(0);
	private Set<AcciPersProp> acciPersProps = new HashSet<AcciPersProp>(0);

	private static final long serialVersionUID = 9196639580323925315L;

	public CentCost() {
	}

	public CentCost(int centCostId, String codigo, String descri, String estado) {
		this.centCostId = centCostId;
		this.codigo = codigo;
		this.descri = descri;
		this.estado = estado;
	}

	public CentCost(int centCostId, String codigo, String descri,
			String estado, Set<AcciPersActu> acciPersActus,
			Set<AcciPersProp> acciPersProps) {
		this.centCostId = centCostId;
		this.codigo = codigo;
		this.descri = descri;
		this.estado = estado;
		this.acciPersActus = acciPersActus;
		this.acciPersProps = acciPersProps;
	}

	@Id
	@TableGenerator(name = "idCentCost", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "cent_cost", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idCentCost")
	@Column(name = "cent_cost_id", unique = true, nullable = false)
	public int getCentCostId() {
		return this.centCostId;
	}

	public void setCentCostId(int centCostId) {
		this.centCostId = centCostId;
	}

	@Column(name = "codigo", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centCost")
	public Set<AcciPersActu> getAcciPersActus() {
		return this.acciPersActus;
	}

	public void setAcciPersActus(Set<AcciPersActu> acciPersActus) {
		this.acciPersActus = acciPersActus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centCost")
	public Set<AcciPersProp> getAcciPersProps() {
		return this.acciPersProps;
	}

	public void setAcciPersProps(Set<AcciPersProp> acciPersProps) {
		this.acciPersProps = acciPersProps;
	}

}
