package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.contabilidad.modelo.PlanCuen;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * DimmPlanCuen generated by hbm2java
 */
@Entity
@Table(name = "dimm_plan_cuen")
@NamedEntityGraph(name = "dimmPlanCuen.Graph", attributeNodes = {
@NamedAttributeNode(value = "planCuen"),
@NamedAttributeNode(value = "dimm")}
)
public class DimmPlanCuen implements java.io.Serializable {

	private Integer dimmPlanCuenId;
	private Dimm dimm;
	private PlanCuen planCuen;
	private String tipoTran;

	private static final long serialVersionUID = 7185389695855425843L;

	public DimmPlanCuen() {
	}

	public DimmPlanCuen(Integer dimmPlanCuenId, Dimm dimm, PlanCuen planCuen,
			String tipoTran) {
		super();
		this.dimmPlanCuenId = dimmPlanCuenId;
		this.dimm = dimm;
		this.planCuen = planCuen;
		this.tipoTran = tipoTran;
	}

	@Id
	@TableGenerator(name = "idDimmPlanCuen", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "dimm_plan_cuen", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idDimmPlanCuen")
	@Column(name = "DIMM_PLAN_CUEN_ID", unique = true, nullable = false)
	public Integer getDimmPlanCuenId() {
		return dimmPlanCuenId;
	}

	public void setDimmPlanCuenId(Integer dimmPlanCuenId) {
		this.dimmPlanCuenId = dimmPlanCuenId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@Column(name = "TIPO_TRAN", nullable = true)
	public String getTipoTran() {
		return tipoTran;
	}

	public void setTipoTran(String tipoTran) {
		this.tipoTran = tipoTran;
	}
}