package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

import ec.com.tecnointel.soem.egreso.modelo.EgreDetaImpu;
import ec.com.tecnointel.soem.egreso.modelo.PersClie;
import ec.com.tecnointel.soem.ingreso.modelo.IngrDetaImpu;
import ec.com.tecnointel.soem.ingreso.modelo.Ingreso;
import ec.com.tecnointel.soem.ingreso.modelo.PersProv;
import ec.com.tecnointel.soem.inventario.modelo.ProdDimm;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Dimm generated by hbm2java
 */
@Entity
@Table(name = "dimm")
public class Dimm implements java.io.Serializable {

	private Integer dimmId;
	private Dimm dimm;
	private String tablaRefe;
	private String tablaDesc;
	private String codigo;
	private String descri;
	private BigDecimal porcen;
	private short factor;
	private LocalDate desde;
	private LocalDate hasta;
	private boolean estado;
	private Set<DocuIngr> docuIngrs = new HashSet<DocuIngr>(0);
	private Set<Dimm> dimms = new HashSet<Dimm>(0);
	private Set<ProdDimm> prodDimms = new HashSet<ProdDimm>(0);
	private Set<PersClie> persClies = new HashSet<PersClie>(0);
	private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);
	private Set<PersProv> persProvs = new HashSet<PersProv>(0);
	private Set<DocuEgre> docuEgres = new HashSet<DocuEgre>(0);
	private Set<FormPago> formPagos = new HashSet<FormPago>(0);
	private Set<EgreDetaImpu> egreDetaImpus = new HashSet<EgreDetaImpu>(0);
	private Set<IngrDetaImpu> ingrDetaImpus = new HashSet<IngrDetaImpu>(0);

	private static final long serialVersionUID = 4234936206426386524L;

	public Dimm() {
	}

	public Dimm(String tablaRefe, String codigo, String descri, boolean estado) {
		this.tablaRefe = tablaRefe;
		this.codigo = codigo;
		this.descri = descri;
		this.estado = estado;
	}

	@Id
	// @TableGenerator(name = "idDimm", table = "Secuencial", pkColumnName =
	// "secuencial_id", pkColumnValue = "13", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator = "idDimm")
	@Column(name = "DIMM_ID", unique = true, nullable = false)
	public Integer getDimmId() {
		return this.dimmId;
	}

	public void setDimmId(Integer dimmId) {
		this.dimmId = dimmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_SUPE_ID")
	public Dimm getDimm() {
		return this.dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@Column(name = "TABLA_REFE", nullable = false, length = 32)
	public String getTablaRefe() {
		return this.tablaRefe;
	}

	public void setTablaRefe(String tablaRefe) {
		this.tablaRefe = tablaRefe;
	}

	@Column(name = "TABLA_DESC", nullable = false, length = 100)
	public String getTablaDesc() {
		return this.tablaDesc;
	}

	public void setTablaDesc(String tablaDesc) {
		this.tablaDesc = tablaDesc;
	}

	@Column(name = "CODIGO", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRI", nullable = false, length = 255)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "PORCEN", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPorcen() {
		return this.porcen;
	}

	public void setPorcen(BigDecimal porcen) {
		this.porcen = porcen;
	}

	@Column(name = "FACTOR", nullable = false)
	public short getFactor() {
		return this.factor;
	}

	public void setFactor(short factor) {
		this.factor = factor;
	}

	@Column(columnDefinition = "DATE", name = "DESDE", nullable = false, length = 10)
	public LocalDate getDesde() {
		return desde;
	}

	public void setDesde(LocalDate desde) {
		this.desde = desde;
	}

	@Column(columnDefinition = "DATE", name = "HASTA", nullable = false, length = 10)
	public LocalDate getHasta() {
		return hasta;
	}

	public void setHasta(LocalDate hasta) {
		this.hasta = hasta;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<DocuIngr> getDocuIngrs() {
		return this.docuIngrs;
	}

	public void setDocuIngrs(Set<DocuIngr> docuIngrs) {
		this.docuIngrs = docuIngrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<Dimm> getDimms() {
		return this.dimms;
	}

	public void setDimms(Set<Dimm> dimms) {
		this.dimms = dimms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<ProdDimm> getProdDimms() {
		return this.prodDimms;
	}

	public void setProdDimms(Set<ProdDimm> prodDimms) {
		this.prodDimms = prodDimms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<PersClie> getPersClies() {
		return this.persClies;
	}

	public void setPersClies(Set<PersClie> persClies) {
		this.persClies = persClies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<Ingreso> getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Set<Ingreso> ingresos) {
		this.ingresos = ingresos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<PersProv> getPersProvs() {
		return this.persProvs;
	}

	public void setPersProvs(Set<PersProv> persProvs) {
		this.persProvs = persProvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<DocuEgre> getDocuEgres() {
		return this.docuEgres;
	}

	public void setDocuEgres(Set<DocuEgre> docuEgres) {
		this.docuEgres = docuEgres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<FormPago> getFormPagos() {
		return this.formPagos;
	}

	public void setFormPagos(Set<FormPago> formPagos) {
		this.formPagos = formPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<EgreDetaImpu> getEgreDetaImpus() {
		return egreDetaImpus;
	}

	public void setEgreDetaImpus(Set<EgreDetaImpu> egreDetaImpus) {
		this.egreDetaImpus = egreDetaImpus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dimm")
	public Set<IngrDetaImpu> getIngrDetaImpus() {
		return ingrDetaImpus;
	}

	public void setIngrDetaImpus(Set<IngrDetaImpu> ingrDetaImpus) {
		this.ingrDetaImpus = ingrDetaImpus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dimmId == null) ? 0 : dimmId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Dimm other = (Dimm) obj;
		if (dimmId == null) {
			if (other.dimmId != null)
				return false;
		} else if (!dimmId.equals(other.dimmId))
			return false;
		return true;
	}
}
