package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import ec.com.tecnointel.soem.caja.modelo.CajaDocuEgre;
import ec.com.tecnointel.soem.egreso.modelo.Egreso;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;

/**
 * DocuEgre generated by hbm2java
 */
@Entity
@Table(name = "docu_egre")
@NamedEntityGraph(name = "docuEgre.Graph", 
attributeNodes = { @NamedAttributeNode(value = "dimm") })
public class DocuEgre implements java.io.Serializable {

	private Integer documentoId;
	private Dimm dimm;
	private Documento documento;
	private short maximoRegi;
	private boolean generaAnex;
	private boolean generaCxc;
	private boolean generaImpu;
	private boolean afectaCaja;
	private String tipoComp;
	private String documeElec;
	private String ambien;
	private String tipoEmis;
	private String forma2;
	private String impresDesc;
	private boolean imprimDire;
	
	private Set<Egreso> egresos = new HashSet<Egreso>(0);
	private Set<CajaDocuEgre> cajaDocuEgres = new HashSet<CajaDocuEgre>(0);

	private static final long serialVersionUID = -5649476949634757731L;

	public DocuEgre() {
	}

	public DocuEgre(Dimm dimm, Documento documento, short maximoRegi, boolean generaAnex, boolean generaCxc, boolean generaImpu,
			boolean afectaCaja, String tipoComp, String documeElec, String ambien, String tipoEmis,
			String forma2, String impresDesc, boolean imprimDire) {
		this.dimm = dimm;
		this.documento = documento;
		this.maximoRegi = maximoRegi;
		this.generaAnex = generaAnex;
		this.generaCxc = generaCxc;
		this.generaImpu = generaImpu;
		this.afectaCaja = afectaCaja;
		this.tipoComp = tipoComp;
		this.documeElec = documeElec;
		this.ambien = ambien;
		this.tipoEmis = tipoEmis;
		this.forma2 = forma2;
		this.impresDesc = impresDesc;
		this.imprimDire = imprimDire;
	}

	public DocuEgre(Dimm dimm, Documento documento, short maximoRegi, boolean generaAnex, boolean generaCxc, boolean generaImpu, 
			boolean afectaCaja, String tipoComp, String documeElec, String ambien, String tipoEmis,
			String forma2, String impresDesc, boolean imprimDire,
			Set<Egreso> egresos, Set<CajaDocuEgre> cajaDocuEgres) {
		this.dimm = dimm;
		this.documento = documento;
		this.maximoRegi = maximoRegi;
		this.generaAnex = generaAnex;
		this.generaCxc = generaCxc;
		this.generaImpu = generaImpu;
		this.afectaCaja = afectaCaja;
		this.tipoComp = tipoComp;
		this.documeElec = documeElec;
		this.ambien = ambien;
		this.tipoEmis = tipoEmis;
		this.forma2 = forma2;
		this.impresDesc = impresDesc;
		this.imprimDire = imprimDire;		
		this.egresos = egresos;
		this.cajaDocuEgres = cajaDocuEgres;
	}

	@Id
	@GenericGenerator(name = "idDocuEgre", strategy = "foreign", parameters = @Parameter(name = "property", value = "documento"))
	@GeneratedValue(generator = "idDocuEgre")
	// @TableGenerator(name = "idDocuEgre", table = "Secuencial", pkColumnName =
	// "secuencial_id", pkColumnValue = "15", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator =
	// "idDocuEgre")
	@Column(name = "DOCUMENTO_ID", unique = true, nullable = false)
	public Integer getDocumentoId() {
		return this.documentoId;
	}

	public void setDocumentoId(Integer documentoId) {
		this.documentoId = documentoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return this.dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@PrimaryKeyJoinColumn
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Min(0)
	@Column(name = "MAXIMO_REGI", nullable = false)
	public short getMaximoRegi() {
		return this.maximoRegi;
	}

	public void setMaximoRegi(short maximoRegi) {
		this.maximoRegi = maximoRegi;
	}

	@Column(name = "GENERA_ANEX", nullable = false)
	public boolean isGeneraAnex() {
		return this.generaAnex;
	}

	public void setGeneraAnex(boolean generaAnex) {
		this.generaAnex = generaAnex;
	}

	@Column(name = "GENERA_CXC", nullable = false)
	public boolean isGeneraCxc() {
		return this.generaCxc;
	}

	public void setGeneraCxc(boolean generaCxc) {
		this.generaCxc = generaCxc;
	}
	
	@Column(name = "GENERA_IMPU", nullable = false)
	public boolean isGeneraImpu() {
		return generaImpu;
	}

	public void setGeneraImpu(boolean generaImpu) {
		this.generaImpu = generaImpu;
	}

	@Column(name = "AFECTA_CAJA", nullable = false)
	public boolean isAfectaCaja() {
		return this.afectaCaja;
	}

	public void setAfectaCaja(boolean afectaCaja) {
		this.afectaCaja = afectaCaja;
	}

	@Column(name = "TIPO_COMP", nullable = false)
	public String getTipoComp() {
		return tipoComp;
	}

	public void setTipoComp(String tipoComp) {
		this.tipoComp = tipoComp;
	}

	@Column(name = "DOCUME_ELEC", nullable = false)
	public String getDocumeElec() {
		return documeElec;
	}

	public void setDocumeElec(String documeElec) {
		this.documeElec = documeElec;
	}


	@Column(name = "AMBIEN", nullable = false)
	public String getAmbien() {
		return ambien;
	}

	public void setAmbien(String ambien) {
		this.ambien = ambien;
	}

	@Column(name = "TIPO_EMIS", nullable = false)
	public String getTipoEmis() {
		return tipoEmis;
	}

	public void setTipoEmis(String tipoEmis) {
		this.tipoEmis = tipoEmis;
	}
	
	@Column(name = "FORMA2", nullable = true, length = 255)
	public String getForma2() {
		return forma2;
	}

	public void setForma2(String forma2) {
		this.forma2 = forma2;
	}

	@Column(name = "IMPRES_DESC", nullable = true, length = 100)
	public String getImpresDesc() {
		return impresDesc;
	}

	public void setImpresDesc(String impresDesc) {
		this.impresDesc = impresDesc;
	}

	@Column(name = "IMPRIM_DIRE", nullable = false)
	public boolean isImprimDire() {
		return imprimDire;
	}

	public void setImprimDire(boolean imprimDire) {
		this.imprimDire = imprimDire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docuEgre")
	public Set<Egreso> getEgresos() {
		return this.egresos;
	}

	public void setEgresos(Set<Egreso> egresos) {
		this.egresos = egresos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docuEgre")
	public Set<CajaDocuEgre> getCajaDocuEgres() {
		return this.cajaDocuEgres;
	}

	public void setCajaDocuEgres(Set<CajaDocuEgre> cajaDocuEgres) {
		this.cajaDocuEgres = cajaDocuEgres;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((documentoId == null) ? 0 : documentoId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DocuEgre other = (DocuEgre) obj;
		if (documentoId == null) {
			if (other.documentoId != null)
				return false;
		} else if (!documentoId.equals(other.documentoId))
			return false;
		return true;
	}
}
