package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import ec.com.tecnointel.soem.caja.modelo.CajaMoviFormPago;
import ec.com.tecnointel.soem.seguridad.modelo.RolFormPago;
import ec.com.tecnointel.soem.tesoreria.modelo.FormPagoMoviIngr;
import ec.com.tecnointel.soem.tesoreria.modelo.FpmeFormPago;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * FormPago generated by hbm2java
 */
@Entity
@Table(name = "form_pago")
@NamedEntityGraph(name = "formPago.Graph", attributeNodes = { 
@NamedAttributeNode(value = "dimm") })
public class FormPago implements java.io.Serializable {

	private Integer formPagoId;
	private Dimm dimm;
	private String descri;
	private String refere;
	private String modulo;
	private String tipo;
	private String tipo2;
	private boolean estado;
//	private Set<FormPagoMoviEgre> formPagoMoviEgres = new HashSet<FormPagoMoviEgre>(0);
	private Set<FormPagoMoviIngr> formPagoMoviIngrs = new HashSet<FormPagoMoviIngr>(0);
	private Set<CajaMoviFormPago> cajaMoviFormPagos = new HashSet<CajaMoviFormPago>(0);
	private Set<RolFormPago> rolFormPagos = new HashSet<RolFormPago>(0);
	private Set<FormPagoPlanCuen> formPagoPlanCuens = new HashSet<FormPagoPlanCuen>(0);
    private Set<FpmeFormPago> fpmeFormPagos = new HashSet<FpmeFormPago>(0);
	
	private static final long serialVersionUID = -4307832358163510001L;

	public FormPago() {
	}

	public FormPago(Integer formPagoId, Dimm dimm, String descri, String refere, 
			String modulo, String tipo, String tipo2, boolean estado) {
		this.formPagoId = formPagoId;
		this.dimm = dimm;
		this.descri = descri;
		this.refere = refere;
		this.modulo = modulo;
		this.tipo = tipo;
		this.tipo2 = tipo2;
		this.estado = estado;
	}

	public FormPago(Integer formPagoId, Dimm dimm, String descri, String refere, 
			String modulo, String tipo, String tipo2, boolean estado, Set<FormPagoMoviIngr> formPagoMoviIngrs,
			Set<CajaMoviFormPago> cajaMoviFormPagos, Set<RolFormPago> rolFormPagos, Set<FpmeFormPago> fpmeFormPagos) {
		this.formPagoId = formPagoId;
		this.dimm = dimm;
		this.descri = descri;
		this.refere = refere;
		this.modulo = modulo;
		this.tipo = tipo;
		this.tipo2 = tipo2;
		this.estado = estado;
//		this.formPagoMoviEgres = formPagoMoviEgres;
		this.formPagoMoviIngrs = formPagoMoviIngrs;
		this.cajaMoviFormPagos = cajaMoviFormPagos;
		this.rolFormPagos = rolFormPagos;
		this.fpmeFormPagos = fpmeFormPagos;
	}

	@Id
	@TableGenerator(name = "idFormPago", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "form_pago", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idFormPago")
	@Column(name = "FORM_PAGO_ID", unique = true, nullable = false)
	public Integer getFormPagoId() {
		return this.formPagoId;
	}

	public void setFormPagoId(Integer formPagoId) {
		this.formPagoId = formPagoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return this.dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "REFERE", nullable = true, length = 32)
	public String getRefere() {
		return this.refere;
	}

	public void setRefere(String refere) {
		this.refere = refere;
	}

	@Column(name = "MODULO", nullable = false)
	public String getModulo() {
		return modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	@Column(name = "TIPO", nullable = false)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formPago")
//	public Set<FormPagoMoviEgre> getFormPagoMoviEgres() {
//		return this.formPagoMoviEgres;
//	}
//
//	public void setFormPagoMoviEgres(Set<FormPagoMoviEgre> formPagoMoviEgres) {
//		this.formPagoMoviEgres = formPagoMoviEgres;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formPago")
	public Set<FormPagoMoviIngr> getFormPagoMoviIngrs() {
		return this.formPagoMoviIngrs;
	}

	public void setFormPagoMoviIngrs(Set<FormPagoMoviIngr> formPagoMoviIngrs) {
		this.formPagoMoviIngrs = formPagoMoviIngrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formPago")
	public Set<CajaMoviFormPago> getCajaMoviFormPagos() {
		return this.cajaMoviFormPagos;
	}

	public void setCajaMoviFormPagos(Set<CajaMoviFormPago> cajaMoviFormPagos) {
		this.cajaMoviFormPagos = cajaMoviFormPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formPago")
	public Set<RolFormPago> getRolFormPagos() {
		return this.rolFormPagos;
	}

	public void setRolFormPagos(Set<RolFormPago> rolFormPagos) {
		this.rolFormPagos = rolFormPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formPago")
	public Set<FormPagoPlanCuen> getFormPagoPlanCuens() {
		return formPagoPlanCuens;
	}

	public void setFormPagoPlanCuens(Set<FormPagoPlanCuen> formPagoPlanCuens) {
		this.formPagoPlanCuens = formPagoPlanCuens;
	}
	
	@OneToMany(fetch=FetchType.LAZY, mappedBy="formPago")
    public Set<FpmeFormPago> getFpmeFormPagos() {
        return this.fpmeFormPagos;
    }
    
    public void setFpmeFormPagos(Set<FpmeFormPago> fpmeFormPagos) {
        this.fpmeFormPagos = fpmeFormPagos;
    }
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((formPagoId == null) ? 0 : formPagoId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		FormPago other = (FormPago) obj;
		if (formPagoId == null) {
			if (other.formPagoId != null)
				return false;
		} else if (!formPagoId.equals(other.formPagoId))
			return false;
		return true;
	}

	public String getTipo2() {
		return tipo2;
	}

	public void setTipo2(String tipo2) {
		this.tipo2 = tipo2;
	}
}
