package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Mapa generated by hbm2java
 */
@Entity
@Table(name = "mapa")
@NamedEntityGraph(name = "mapa.Graph", attributeNodes = { 
@NamedAttributeNode(value = "mapaNive") })
public class Mapa implements java.io.Serializable {

	private Integer mapaId;
	private Mapa mapa;
	private MapaNive mapaNive;
	private String descri;
	private boolean detall;
	private boolean estado;
	private Set<Mapa> mapas = new HashSet<Mapa>(0);

	private static final long serialVersionUID = 3058686350439853662L;

	public Mapa() {
	}

	public Mapa(Integer mapaId, MapaNive mapaNive, String descri, boolean detall, boolean estado) {
		this.mapaId = mapaId;
		this.mapaNive = mapaNive;
		this.descri = descri;
		this.detall = detall;
		this.estado = estado;
	}

	public Mapa(Integer mapaId, Mapa mapa, MapaNive mapaNive, String descri, boolean detall, boolean estado,
			Set<Mapa> mapas) {
		this.mapaId = mapaId;
		this.mapa = mapa;
		this.mapaNive = mapaNive;
		this.descri = descri;
		this.detall = detall;
		this.estado = estado;
		this.mapas = mapas;
	}

	@Id
	@TableGenerator(name = "idMapa", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "mapa", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idMapa")
	@Column(name = "MAPA_ID", unique = true, nullable = false)
	public Integer getMapaId() {
		return this.mapaId;
	}

	public void setMapaId(Integer mapaId) {
		this.mapaId = mapaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPA_SUPE_ID")
	public Mapa getMapa() {
		return this.mapa;
	}

	public void setMapa(Mapa mapa) {
		this.mapa = mapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAPA_NIVE_ID", nullable = false)
	public MapaNive getMapaNive() {
		return this.mapaNive;
	}

	public void setMapaNive(MapaNive mapaNive) {
		this.mapaNive = mapaNive;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "DETALL", nullable = false)
	public boolean isDetall() {
		return this.detall;
	}

	public void setDetall(boolean detall) {
		this.detall = detall;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mapa")
	public Set<Mapa> getMapas() {
		return this.mapas;
	}

	public void setMapas(Set<Mapa> mapas) {
		this.mapas = mapas;
	}

}
