package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Parametro generated by hbm2java
 */
@Entity
@Table(name = "parametro")
public class Parametro implements java.io.Serializable {

	private Integer parametroId;
	private String codigo;
	private String descri;
	private boolean estado;
//	private Set<Egreso> egresos = new HashSet<Egreso>(0);
	private Set<PersPara> persParas = new HashSet<PersPara>(0);
	private Set<SucuPara> sucuParas = new HashSet<SucuPara>(0);
	
	private static final long serialVersionUID = -7718255426827783860L;

	public Parametro() {
	}

//	public Parametro(Integer parametroId, String codigo, String descri, boolean estado) {
//		this.parametroId = parametroId;
//		this.codigo = codigo;
//		this.descri = descri;
//		this.estado = estado;
//	}

	public Parametro(Integer parametroId) {
		this.parametroId = parametroId;
	}

	@Id
	// @TableGenerator(name = "idParametro", table = "Secuencial", pkColumnName
	// = "secuencial_id", pkColumnValue = "34", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator =
	// "idParametro")
	@Column(name = "PARAMETRO_ID", unique = true, nullable = false)
	public Integer getParametroId() {
		return this.parametroId;
	}

	public void setParametroId(Integer parametroId) {
		this.parametroId = parametroId;
	}

	@Column(name = "CODIGO", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametro")
	public Set<PersPara> getPersParas() {
		return this.persParas;
	}

	public void setPersParas(Set<PersPara> persParas) {
		this.persParas = persParas;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametro")
	public Set<SucuPara> getSucuParas() {
		return sucuParas;
	}

	public void setSucuParas(Set<SucuPara> sucuParas) {
		this.sucuParas = sucuParas;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Parametro other = (Parametro) obj;
		if (parametroId == null) {
			if (other.parametroId != null)
				return false;
		} else if (!parametroId.equals(other.parametroId))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((parametroId == null) ? 0 : parametroId.hashCode());
		return result;
	}

}
