package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * PersPara generated by hbm2java
 */
@Entity
@Table(name = "pers_para")
public class PersPara implements java.io.Serializable {

	private Integer persParaId;
	private Parametro parametro;
	private Persona persona;
	private String descri;
	private short priori;

	private static final long serialVersionUID = -1935575692309972516L;

	public PersPara() {
	}

	public PersPara(Integer persParaId, Parametro parametro, Persona persona, String descri, short priori) {
		this.persParaId = persParaId;
		this.parametro = parametro;
		this.persona = persona;
		this.descri = descri;
		this.priori = priori;
	}

	@Id
	@TableGenerator(name = "idPersPara", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "pers_para", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idPersPara")
	@Column(name = "PERS_PARA_ID", unique = true, nullable = false)
	public Integer getPersParaId() {
		return this.persParaId;
	}

	public void setPersParaId(Integer persParaId) {
		this.persParaId = persParaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PARAMETRO_ID", nullable = false)
	public Parametro getParametro() {
		return this.parametro;
	}

	public void setParametro(Parametro parametro) {
		this.parametro = parametro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONA_ID", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "DESCRI", nullable = false)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "PRIORI", nullable = false)
	public short getPriori() {
		return this.priori;
	}

	public void setPriori(short priori) {
		this.priori = priori;
	}

}
