package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import ec.com.tecnointel.soem.egreso.modelo.EgreDeta;
import ec.com.tecnointel.soem.ingreso.modelo.IngrDeta;
import ec.com.tecnointel.soem.ingreso.modelo.IngrDetaPrec;
import ec.com.tecnointel.soem.inventario.modelo.ProdPrec;
import ec.com.tecnointel.soem.seguridad.modelo.RolPrec;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Precio generated by hbm2java
 */
@Entity
@Table(name = "precio")
public class Precio implements java.io.Serializable {

	private Integer precioId;
	private String codigo;
	private String descri;
	private Integer alcanc;
	private BigDecimal factor;
	private boolean estado;
	private Set<SucuPrec> sucuPrecs = new HashSet<SucuPrec>(0);
	private Set<RolPrec> rolPrecs = new HashSet<RolPrec>(0);
	private Set<ProdPrec> prodPrecs = new HashSet<ProdPrec>(0);
	private Set<IngrDeta> ingrDetas = new HashSet<IngrDeta>(0);
	private Set<IngrDetaPrec> ingrDetaPrecs = new HashSet<IngrDetaPrec>(0);
	private Set<EgreDeta> egreDetas = new HashSet<EgreDeta>(0);

	private static final long serialVersionUID = 7248531289001144622L;

	public Precio() {
	}

	public Precio(Integer precioId, String codigo, String descri, Integer alcanc, BigDecimal factor, boolean estado) {
		this.precioId = precioId;
		this.codigo = codigo;
		this.descri = descri;
		this.alcanc = alcanc;
		this.factor = factor;
		this.estado = estado;
	}

	public Precio(Integer precioId, String codigo, String descri, Integer alcanc, BigDecimal factor, boolean estado,
			Set<SucuPrec> sucuPrecs, Set<RolPrec> rolPrecs, Set<ProdPrec> prodPrecs, 
			Set<IngrDeta> ingrDetas, Set<IngrDetaPrec> ingrDetaPrecs, Set<EgreDeta> egreDetas) {
		this.precioId = precioId;
		this.codigo = codigo;
		this.descri = descri;
		this.alcanc = alcanc;
		this.factor = factor;
		this.estado = estado;
		this.sucuPrecs = sucuPrecs;
		this.rolPrecs = rolPrecs;
		this.prodPrecs = prodPrecs;
		this.ingrDetas = ingrDetas;
		this.ingrDetaPrecs = ingrDetaPrecs;
		this.egreDetas = egreDetas;
	}

	@Id
	@TableGenerator(name = "idPrecio", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "precio", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idPrecio")
	@Column(name = "PRECIO_ID", unique = true, nullable = false)
	public Integer getPrecioId() {
		return this.precioId;
	}

	public void setPrecioId(Integer precioId) {
		this.precioId = precioId;
	}

	@Column(name = "CODIGO", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "ALCANC", nullable = false)
	public Integer getAlcanc() {
		return alcanc;
	}

	public void setAlcanc(Integer alcanc) {
		this.alcanc = alcanc;
	}

	@Column(name = "FACTOR", nullable = false, precision = 12, scale = 6)
	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio")
	public Set<SucuPrec> getSucuPrecs() {
		return this.sucuPrecs;
	}

	public void setSucuPrecs(Set<SucuPrec> sucuPrecs) {
		this.sucuPrecs = sucuPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio", cascade = {CascadeType.REMOVE})
	public Set<RolPrec> getRolPrecs() {
		return this.rolPrecs;
	}

	public void setRolPrecs(Set<RolPrec> rolPrecs) {
		this.rolPrecs = rolPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio", cascade = {CascadeType.REMOVE})
	public Set<ProdPrec> getProdPrecs() {
		return this.prodPrecs;
	}

	public void setProdPrecs(Set<ProdPrec> prodPrecs) {
		this.prodPrecs = prodPrecs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio")
	public Set<IngrDeta> getIngrDetas() {
		return ingrDetas;
	}

	public void setIngrDetas(Set<IngrDeta> ingrDetas) {
		this.ingrDetas = ingrDetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio")
	public Set<IngrDetaPrec> getIngrDetaPrecs() {
		return ingrDetaPrecs;
	}

	public void setIngrDetaPrecs(Set<IngrDetaPrec> ingrDetaPrecs) {
		this.ingrDetaPrecs = ingrDetaPrecs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "precio")
	public Set<EgreDeta> getEgreDetas() {
		return this.egreDetas;
	}

	public void setEgreDetas(Set<EgreDeta> egreDetas) {
		this.egreDetas = egreDetas;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((precioId == null) ? 0 : precioId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Precio other = (Precio) obj;
		if (precioId == null) {
			if (other.precioId != null)
				return false;
		} else if (!precioId.equals(other.precioId))
			return false;
		return true;
	}
}
