package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * SucuBode generated by hbm2java
 */
@Entity
@Table(name = "sucu_bode")
@NamedEntityGraph(name = "sucuBode.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"), 
@NamedAttributeNode(value = "bodega") })
public class SucuBode implements java.io.Serializable {

	private Integer sucuBodeId;
	private Bodega bodega;
	private Sucursal sucursal;
	private Boolean acceso;

	private static final long serialVersionUID = -7914878111607168940L;

	public SucuBode() {
	}

	public SucuBode(Integer sucuBodeId, Bodega bodega, Sucursal sucursal, Boolean acceso) {
		this.sucuBodeId = sucuBodeId;
		this.bodega = bodega;
		this.sucursal = sucursal;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idSucuBode", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "sucu_bode", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idSucuBode")
	@Column(name = "SUCU_BODE_ID", unique = true, nullable = false)
	public Integer getSucuBodeId() {
		return this.sucuBodeId;
	}

	public void setSucuBodeId(Integer sucuBodeId) {
		this.sucuBodeId = sucuBodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BODEGA_ID", nullable = false)
	public Bodega getBodega() {
		return this.bodega;
	}

	public void setBodega(Bodega bodega) {
		this.bodega = bodega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

}
