package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import ec.com.tecnointel.soem.caja.modelo.Caja;
import ec.com.tecnointel.soem.caja.modelo.CajaMovi;
import ec.com.tecnointel.soem.egreso.modelo.Egreso;
import ec.com.tecnointel.soem.ingreso.modelo.Ingreso;
import ec.com.tecnointel.soem.inventario.modelo.Kardex;
import ec.com.tecnointel.soem.inventario.modelo.ProdBode;
import ec.com.tecnointel.soem.inventario.modelo.ProdCost;
import ec.com.tecnointel.soem.inventario.modelo.ProdPrec;
import ec.com.tecnointel.soem.inventario.modelo.TomaFisi;
import ec.com.tecnointel.soem.seguridad.modelo.Auditoria;
import ec.com.tecnointel.soem.seguridad.modelo.RolBode;
import ec.com.tecnointel.soem.seguridad.modelo.RolPrec;
import ec.com.tecnointel.soem.seguridad.modelo.RolSucu;
import ec.com.tecnointel.soem.tesoreria.modelo.FormPagoMoviEgre;
import ec.com.tecnointel.soem.tesoreria.modelo.FormPagoMoviIngr;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.NamedSubgraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.validation.constraints.NotNull;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal")
@NamedEntityGraph(name = "sucursal.Graph", attributeNodes = { 
@NamedAttributeNode(value = "sucuCertEmis", subgraph = "certEmis.Graph")} ,
subgraphs = {
		@NamedSubgraph(name = "certEmis.Graph",attributeNodes = { 
		@NamedAttributeNode(value = "certEmis") })
})
public class Sucursal implements java.io.Serializable {

	private Integer sucursalId;
	private String codigo;
	private boolean matriz;
	private String descri;
	private String ruc;
	private String razonSoci;
	private String nombreCome;
	private String ciudad;
	private String direcc;
	private String direccEsta;
	private String telef1;
	private String telef2;
	private String correo;
	private String repres;
	private String represCedu;
	private String represDire;
	private String rucCont;
	private String contriEspe;
	private boolean obligaCont;
	private String logoti;
	private Boolean estado;
	
	private SucuCertEmis sucuCertEmis;
	
	private Set<Auditoria> auditorias = new HashSet<Auditoria>(0);
	private Set<SucuPrec> sucuPrecs = new HashSet<SucuPrec>(0);
	private Set<ProdPrec> prodPrecs = new HashSet<ProdPrec>(0);
	private Set<RolSucu> rolSucus = new HashSet<RolSucu>(0);
	private Set<ProdBode> prodBodes = new HashSet<ProdBode>(0);
	private Set<FormPagoMoviIngr> formPagoMoviIngrs = new HashSet<FormPagoMoviIngr>(0);
	private Set<ProdCost> prodCosts = new HashSet<ProdCost>(0);
	private Set<CajaMovi> cajaMovis = new HashSet<CajaMovi>(0);
	private Set<RolBode> rolBodes = new HashSet<RolBode>(0);
	private Set<FormPagoMoviEgre> formPagoMoviEgres = new HashSet<FormPagoMoviEgre>(0);
	private Set<Ingreso> ingresos = new HashSet<Ingreso>(0);
	private Set<SucuBode> sucuBodes = new HashSet<SucuBode>(0);
	private Set<Caja> cajas = new HashSet<Caja>(0);
	private Set<Egreso> egresos = new HashSet<Egreso>(0);
	private Set<RolPrec> rolPrecs = new HashSet<RolPrec>(0);
	private Set<Kardex> kardexs = new HashSet<Kardex>(0);
	private Set<TomaFisi> tomaFisis = new HashSet<TomaFisi>(0);
	private Set<SucuPara> sucuParas = new HashSet<SucuPara>(0);
	
	private static final long serialVersionUID = 6697823983141541154L;

	public Sucursal() {
	}

	public Sucursal(Integer sucursalId, String codigo, boolean matriz, String descri, String ruc, String ciudad,
			String direcc, String direccEsta, String telef1, String correo, String repres, String represCedu,
			String represDire, String rucCont, String contriEspe, boolean obligaCont) {
		this.sucursalId = sucursalId;
		this.codigo = codigo;
		this.matriz = matriz;
		this.descri = descri;
		this.ruc = ruc;
		this.ciudad = ciudad;
		this.direcc = direcc;
		this.direccEsta = direccEsta;
		this.telef1 = telef1;
		this.correo = correo;
		this.repres = repres;
		this.represCedu = represCedu;
		this.represDire = represDire;
		this.rucCont = rucCont;
		this.contriEspe = contriEspe;
		this.obligaCont = obligaCont;
	}

	public Sucursal(Integer sucursalId, String codigo, boolean matriz, String descri, String ruc, String ciudad,
			String direcc, String direccEsta, String telef1, String telef2, String correo, String repres,
			String represCedu, String represDire, String rucCont, String contriEspe, boolean obligaCont, String logoti,
			Set<Auditoria> auditorias, Set<SucuPrec> sucuPrecs, Set<ProdPrec> prodPrecs, Set<RolSucu> rolSucus,
			Set<ProdBode> prodBodes, Set<FormPagoMoviIngr> formPagoMoviIngrs, Set<ProdCost> prodCosts,
			Set<CajaMovi> cajaMovis, Set<RolBode> rolBodes, Set<FormPagoMoviEgre> formPagoMoviEgres,
			Set<Ingreso> ingresos, Set<SucuBode> sucuBodes, Set<Caja> cajas, Set<Egreso> egresos, Set<RolPrec> rolPrecs,
			Set<Kardex> kardexs, Set<TomaFisi> tomaFisis) {
		this.sucursalId = sucursalId;
		this.codigo = codigo;
		this.matriz = matriz;
		this.descri = descri;
		this.ruc = ruc;
		this.ciudad = ciudad;
		this.direcc = direcc;
		this.direccEsta = direccEsta;
		this.telef1 = telef1;
		this.telef2 = telef2;
		this.correo = correo;
		this.repres = repres;
		this.represCedu = represCedu;
		this.represDire = represDire;
		this.rucCont = rucCont;
		this.contriEspe = contriEspe;
		this.obligaCont = obligaCont;
		this.logoti = logoti;
		this.auditorias = auditorias;
		this.sucuPrecs = sucuPrecs;
		this.prodPrecs = prodPrecs;
		this.rolSucus = rolSucus;
		this.prodBodes = prodBodes;
		this.formPagoMoviIngrs = formPagoMoviIngrs;
		this.prodCosts = prodCosts;
		this.cajaMovis = cajaMovis;
		this.rolBodes = rolBodes;
		this.formPagoMoviEgres = formPagoMoviEgres;
		this.ingresos = ingresos;
		this.sucuBodes = sucuBodes;
		this.cajas = cajas;
		this.egresos = egresos;
		this.rolPrecs = rolPrecs;
		this.kardexs = kardexs;
		this.tomaFisis = tomaFisis;
	}

	@Id
	@TableGenerator(name = "idSucursal", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "sucursal", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idSucursal")
	@Column(name = "SUCURSAL_ID", unique = true, nullable = false)
	public Integer getSucursalId() {
		return this.sucursalId;
	}

	public void setSucursalId(Integer sucursalId) {
		this.sucursalId = sucursalId;
	}

	@Column(name = "CODIGO", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "MATRIZ", nullable = false)
	public boolean isMatriz() {
		return this.matriz;
	}

	public void setMatriz(boolean matriz) {
		this.matriz = matriz;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "RUC", nullable = false, length = 13)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "RAZON_SOCI", nullable = false, length = 256)
	public String getRazonSoci() {
		return razonSoci;
	}

	public void setRazonSoci(String razonSoci) {
		this.razonSoci = razonSoci;
	}

	@Column(name = "NOMBRE_COME", nullable = false, length = 256)
	public String getNombreCome() {
		return nombreCome;
	}

	public void setNombreCome(String nombreCome) {
		this.nombreCome = nombreCome;
	}
	
	@Column(name = "CIUDAD", nullable = false, length = 100)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "DIRECC", nullable = false, length = 100)
	public String getDirecc() {
		return this.direcc;
	}

	public void setDirecc(String direcc) {
		this.direcc = direcc;
	}

	@Column(name = "DIRECC_ESTA", nullable = true, length = 100)
	public String getDireccEsta() {
		return direccEsta;
	}

	public void setDireccEsta(String direccEsta) {
		this.direccEsta = direccEsta;
	}

	@Column(name = "TELEF1", nullable = false, length = 10)
	public String getTelef1() {
		return this.telef1;
	}

	public void setTelef1(String telef1) {
		this.telef1 = telef1;
	}

	@Column(name = "TELEF2", length = 10)
	public String getTelef2() {
		return this.telef2;
	}

	public void setTelef2(String telef2) {
		this.telef2 = telef2;
	}

	@Column(name = "CORREO", nullable = false, length = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "REPRES", nullable = false, length = 100)
	public String getRepres() {
		return this.repres;
	}

	public void setRepres(String repres) {
		this.repres = repres;
	}

	@Column(name = "REPRES_CEDU", nullable = false, length = 13)
	public String getRepresCedu() {
		return this.represCedu;
	}

	public void setRepresCedu(String represCedu) {
		this.represCedu = represCedu;
	}

	@Column(name = "REPRES_DIRE", nullable = false, length = 100)
	public String getRepresDire() {
		return this.represDire;
	}

	public void setRepresDire(String represDire) {
		this.represDire = represDire;
	}

	@Column(name = "RUC_CONT", nullable = false, length = 13)
	public String getRucCont() {
		return this.rucCont;
	}

	public void setRucCont(String rucCont) {
		this.rucCont = rucCont;
	}

	@Column(name = "CONTRI_ESPE", nullable = true, length = 13)
	public String getContriEspe() {
		return this.contriEspe;
	}

	public void setContriEspe(String contriEspe) {
		this.contriEspe = contriEspe;
	}

	@Column(name = "OBLIGA_CONT", nullable = false)
	public boolean isObligaCont() {
		return this.obligaCont;
	}

	public void setObligaCont(boolean obligaCont) {
		this.obligaCont = obligaCont;
	}

	@Column(name = "LOGOTI")
	public String getLogoti() {
		return this.logoti;
	}

	public void setLogoti(String logoti) {
		this.logoti = logoti;
	}

	@NotNull
	@Column(name = "ESTADO")
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Auditoria> getAuditorias() {
		return this.auditorias;
	}

	public void setAuditorias(Set<Auditoria> auditorias) {
		this.auditorias = auditorias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<SucuPrec> getSucuPrecs() {
		return this.sucuPrecs;
	}

	public void setSucuPrecs(Set<SucuPrec> sucuPrecs) {
		this.sucuPrecs = sucuPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<ProdPrec> getProdPrecs() {
		return this.prodPrecs;
	}

	public void setProdPrecs(Set<ProdPrec> prodPrecs) {
		this.prodPrecs = prodPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<RolSucu> getRolSucus() {
		return this.rolSucus;
	}

	public void setRolSucus(Set<RolSucu> rolSucus) {
		this.rolSucus = rolSucus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<ProdBode> getProdBodes() {
		return this.prodBodes;
	}

	public void setProdBodes(Set<ProdBode> prodBodes) {
		this.prodBodes = prodBodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<FormPagoMoviIngr> getFormPagoMoviIngrs() {
		return this.formPagoMoviIngrs;
	}

	public void setFormPagoMoviIngrs(Set<FormPagoMoviIngr> formPagoMoviIngrs) {
		this.formPagoMoviIngrs = formPagoMoviIngrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<ProdCost> getProdCosts() {
		return this.prodCosts;
	}

	public void setProdCosts(Set<ProdCost> prodCosts) {
		this.prodCosts = prodCosts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<CajaMovi> getCajaMovis() {
		return this.cajaMovis;
	}

	public void setCajaMovis(Set<CajaMovi> cajaMovis) {
		this.cajaMovis = cajaMovis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<RolBode> getRolBodes() {
		return this.rolBodes;
	}

	public void setRolBodes(Set<RolBode> rolBodes) {
		this.rolBodes = rolBodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<FormPagoMoviEgre> getFormPagoMoviEgres() {
		return this.formPagoMoviEgres;
	}

	public void setFormPagoMoviEgres(Set<FormPagoMoviEgre> formPagoMoviEgres) {
		this.formPagoMoviEgres = formPagoMoviEgres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Ingreso> getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Set<Ingreso> ingresos) {
		this.ingresos = ingresos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<SucuBode> getSucuBodes() {
		return this.sucuBodes;
	}

	public void setSucuBodes(Set<SucuBode> sucuBodes) {
		this.sucuBodes = sucuBodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Caja> getCajas() {
		return this.cajas;
	}

	public void setCajas(Set<Caja> cajas) {
		this.cajas = cajas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Egreso> getEgresos() {
		return this.egresos;
	}

	public void setEgresos(Set<Egreso> egresos) {
		this.egresos = egresos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<RolPrec> getRolPrecs() {
		return this.rolPrecs;
	}

	public void setRolPrecs(Set<RolPrec> rolPrecs) {
		this.rolPrecs = rolPrecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Kardex> getKardexs() {
		return kardexs;
	}

	public void setKardexs(Set<Kardex> kardexs) {
		this.kardexs = kardexs;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set<TomaFisi> getTomaFisis() {
        return this.tomaFisis;
    }
    
    public void setTomaFisis(Set<TomaFisi> tomaFisis) {
        this.tomaFisis = tomaFisis;
    }
    
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<SucuPara> getSucuParas() {
		return sucuParas;
	}

	public void setSucuParas(Set<SucuPara> sucuParas) {
		this.sucuParas = sucuParas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public SucuCertEmis getSucuCertEmis() {
		return sucuCertEmis;
	}

	public void setSucuCertEmis(SucuCertEmis sucuCertEmis) {
		this.sucuCertEmis = sucuCertEmis;
	}

    @Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sucursalId == null) ? 0 : sucursalId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Sucursal other = (Sucursal) obj;
		if (sucursalId == null) {
			if (other.sucursalId != null)
				return false;
		} else if (!sucursalId.equals(other.sucursalId))
			return false;
		return true;
	}
}
