package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * SucuPrec generated by hbm2java
 */
@Entity
@Table(name = "sucu_prec")
@NamedEntityGraph(name = "sucuPrec.Graph", attributeNodes = {
@NamedAttributeNode(value = "sucursal"),
@NamedAttributeNode(value = "precio") })
public class SucuPrec implements java.io.Serializable {

	private Integer sucuPrecId;
	private Precio precio;
	private Sucursal sucursal;
	private Boolean acceso;

	private static final long serialVersionUID = 1379487222482060231L;

	public SucuPrec() {
	}

	public SucuPrec(Integer sucuPrecId, Precio precio, Sucursal sucursal, Boolean acceso) {
		this.sucuPrecId = sucuPrecId;
		this.precio = precio;
		this.sucursal = sucursal;
		this.acceso = acceso;
	}

	@Id
	@TableGenerator(name = "idSucuPrec", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "sucu_prec", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idSucuPrec")
	@Column(name = "SUCU_PREC_ID", unique = true, nullable = false)
	public Integer getSucuPrecId() {
		return this.sucuPrecId;
	}

	public void setSucuPrecId(Integer sucuPrecId) {
		this.sucuPrecId = sucuPrecId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRECIO_ID", nullable = false)
	public Precio getPrecio() {
		return this.precio;
	}

	public void setPrecio(Precio precio) {
		this.precio = precio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUCURSAL_ID", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "ACCESO", nullable = false)
	public Boolean getAcceso() {
		return acceso;
	}

	public void setAcceso(Boolean acceso) {
		this.acceso = acceso;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((precio == null) ? 0 : precio.hashCode());
		result = prime * result + ((sucursal == null) ? 0 : sucursal.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SucuPrec other = (SucuPrec) obj;
		if (precio == null) {
			if (other.precio != null)
				return false;
		} else if (!precio.equals(other.precio))
			return false;
		if (sucursal == null) {
			if (other.sucursal != null)
				return false;
		} else if (!sucursal.equals(other.sucursal))
			return false;
		return true;
	}

}
