package ec.com.tecnointel.soem.parametro.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name = "tran_plan")
public class TranPlan implements java.io.Serializable {

	private Integer tranPlanId;
	private String descri;
	private String modulo;
	private String tipo;
	private boolean estado;
	
	private Set<TranPlanDeta> tranPlanDetas = new HashSet<TranPlanDeta>(0);

	private static final long serialVersionUID = -3375611786633417530L;

	public TranPlan() {
	}

	public TranPlan(Integer tranPlanId, String descri, String modulo, String tipo, boolean estado) {
		this.tranPlanId = tranPlanId;
		this.descri = descri;
		this.modulo = modulo;
		this.tipo = tipo;
		this.estado = estado;
	}

	public TranPlan(Integer tranPlanId, String descri, String modulo, String tipo, boolean estado, Set<TranPlanDeta> tranPlanDetas) {
		this.tranPlanId = tranPlanId;
		this.descri = descri;
		this.modulo = modulo;
		this.tipo = tipo;
		this.estado = estado;
		this.tranPlanDetas = tranPlanDetas;
	}

	@Id
	@TableGenerator(name = "idTranPlan", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "tran_plan", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idTranPlan")
	@Column(name = "TRAN_PLAN_ID", unique = true, nullable = false)
	public Integer getTranPlanId() {
		return tranPlanId;
	}

	public void setTranPlanId(Integer tranPlanId) {
		this.tranPlanId = tranPlanId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "MODULO", nullable = false, length = 15)
	public String getModulo() {
		return modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	@Column(name = "TIPO", nullable = false, length = 15)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tranPlan")
	public Set<TranPlanDeta> getTranPlanDetas() {
		return tranPlanDetas;
	}

	public void setTranPlanDetas(Set<TranPlanDeta> tranPlanDetas) {
		this.tranPlanDetas = tranPlanDetas;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((tranPlanId == null) ? 0 : tranPlanId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TranPlan other = (TranPlan) obj;
		if (tranPlanId == null) {
			if (other.tranPlanId != null)
				return false;
		} else if (!tranPlanId.equals(other.tranPlanId))
			return false;
		return true;
	}
}
