package ec.com.tecnointel.soem.egreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import ec.com.tecnointel.soem.contabilidad.modelo.PlanCuen;
import ec.com.tecnointel.soem.parametro.modelo.Documento;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ClieGrupPlanCuen generated by hbm2java
 */
@Entity
@Table(name = "clie_grup_plan_cuen")
@NamedEntityGraph(name = "cgpc.Graph", attributeNodes = {
@NamedAttributeNode(value = "clieGrup"),
@NamedAttributeNode(value = "planCuen"),
@NamedAttributeNode(value = "documento") })
public class ClieGrupPlanCuen implements java.io.Serializable {

	private Integer cgpcId;
	private ClieGrup clieGrup;
	private PlanCuen planCuen;
	private Documento documento;
	private String tipoTran;

	private static final long serialVersionUID = 5279764612893511206L;

	public ClieGrupPlanCuen() {
	}

	public ClieGrupPlanCuen(Integer cgpcId, ClieGrup clieGrup, PlanCuen planCuen, String tipoTran) {
		this.cgpcId = cgpcId;
		this.clieGrup = clieGrup;
		this.planCuen = planCuen;
		this.tipoTran = tipoTran;
	}

	@Id
	@TableGenerator(name = "idClieGrupPlanCuen", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "clie_grup_plan_cuen", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idClieGrupPlanCuen")
	@Column(name = "CGPC_ID", unique = true, nullable = false)
	public Integer getCgpcId() {
		return this.cgpcId;
	}

	public void setCgpcId(Integer cgpcId) {
		this.cgpcId = cgpcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIE_GRUP_ID", nullable = false)
	public ClieGrup getClieGrup() {
		return this.clieGrup;
	}

	public void setClieGrup(ClieGrup clieGrup) {
		this.clieGrup = clieGrup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_CUEN_ID", nullable = false)
	public PlanCuen getPlanCuen() {
		return this.planCuen;
	}

	public void setPlanCuen(PlanCuen planCuen) {
		this.planCuen = planCuen;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCUMENTO_ID", nullable = false)
	public Documento getDocumento() {
		return documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "TIPO_TRAN")
	public String getTipoTran() {
		return tipoTran;
	}

	public void setTipoTran(String tipoTran) {
		this.tipoTran = tipoTran;
	}
}
