package ec.com.tecnointel.soem.egreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * ClieGrup generated by hbm2java
 */
@Entity
@Table(name = "clie_grup")
public class ClieGrup implements java.io.Serializable {

	private Integer clieGrupId;
	private String descri;
	private String nota;
	private boolean estado;
	private Set<ClieGrupPlanCuen> clieGrupPlanCuens = new HashSet<ClieGrupPlanCuen>(0);
	private Set<PersClie> persClies = new HashSet<PersClie>(0);

	private static final long serialVersionUID = -3920713504541064058L;

	public ClieGrup() {
	}

	public ClieGrup(Integer clieGrupId, String descri, boolean estado) {
		this.clieGrupId = clieGrupId;
		this.descri = descri;
		this.estado = estado;
	}

	public ClieGrup(Integer clieGrupId, String descri, String nota, boolean estado,
			Set<ClieGrupPlanCuen> clieGrupPlanCuens, Set<PersClie> persClies) {
		this.clieGrupId = clieGrupId;
		this.descri = descri;
		this.nota = nota;
		this.estado = estado;
		this.clieGrupPlanCuens = clieGrupPlanCuens;
		this.persClies = persClies;
	}

	@Id
	@TableGenerator(name = "idClieGrup", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "clie_grup", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idClieGrup")
	@Column(name = "CLIE_GRUP_ID", unique = true, nullable = false)
	public Integer getClieGrupId() {
		return this.clieGrupId;
	}

	public void setClieGrupId(Integer clieGrupId) {
		this.clieGrupId = clieGrupId;
	}

	@Column(name = "DESCRI", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clieGrup")
	public Set<ClieGrupPlanCuen> getClieGrupPlanCuens() {
		return this.clieGrupPlanCuens;
	}

	public void setClieGrupPlanCuens(Set<ClieGrupPlanCuen> clieGrupPlanCuens) {
		this.clieGrupPlanCuens = clieGrupPlanCuens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clieGrup")
	public Set<PersClie> getPersClies() {
		return this.persClies;
	}

	public void setPersClies(Set<PersClie> persClies) {
		this.persClies = persClies;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((clieGrupId == null) ? 0 : clieGrupId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClieGrup other = (ClieGrup) obj;
		if (clieGrupId == null) {
			if (other.clieGrupId != null)
				return false;
		} else if (!clieGrupId.equals(other.clieGrupId))
			return false;
		return true;
	}

}
