package ec.com.tecnointel.soem.egreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;

import ec.com.tecnointel.soem.parametro.modelo.Dimm;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * EgreDetaImpu generated by hbm2java
 */
@Entity
@Table(name = "egre_deta_impu")
public class EgreDetaImpu implements java.io.Serializable {

	private Integer egreDetaImpuId;
	private Dimm dimm;
	private EgreDeta egreDeta;
	private String descri;
	private String codigo;
	private BigDecimal porcen;

	private String tipo;
	private short factor;

	private static final long serialVersionUID = -5179251575476317221L;

	public EgreDetaImpu() {
	}

	public EgreDetaImpu(Integer egreDetaImpuId, EgreDeta egreDeta, String descri, String codigo, BigDecimal porcen,
			String tipo, short factor) {
		this.egreDetaImpuId = egreDetaImpuId;
		this.egreDeta = egreDeta;
		this.descri = descri;
		this.codigo = codigo;
		this.porcen = porcen;
		this.tipo = tipo;
		this.factor = factor;
	}

	@Id
	@TableGenerator(name = "idEgreDetaImpu", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "egre_deta_impu", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEgreDetaImpu")
	@Column(name = "EGRE_DETA_IMPU_ID", unique = true, nullable = false)
	public Integer getEgreDetaImpuId() {
		return this.egreDetaImpuId;
	}

	public void setEgreDetaImpuId(Integer egreDetaImpuId) {
		this.egreDetaImpuId = egreDetaImpuId;
	}

	@Column(name = "DESCRI", nullable = false, length = 255)
	public String getDescri() {
		return descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "CODIGO", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "PORCEN", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPorcen() {
		return this.porcen;
	}

	public void setPorcen(BigDecimal porcen) {
		this.porcen = porcen;
	}

	@Column(name = "TIPO", nullable = false, length = 3)
	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "FACTOR", nullable = false)
	public short getFactor() {
		return this.factor;
	}

	public void setFactor(short factor) {
		this.factor = factor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EGRE_DETA_ID", nullable = false)
	public EgreDeta getEgreDeta() {
		return this.egreDeta;
	}

	public void setEgreDeta(EgreDeta egreDeta) {
		this.egreDeta = egreDeta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}
}
