package ec.com.tecnointel.soem.egreso.modelo;
// Generated 26-jul-2016 22:29:48 by Hibernate Tools 5.1.0.Alpha2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import ec.com.tecnointel.soem.parametro.modelo.Dimm;
import ec.com.tecnointel.soem.parametro.modelo.Persona;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedAttributeNode;
import jakarta.persistence.NamedEntityGraph;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;

/**
 * PersClie generated by hbm2java
 */
@Entity
@Table(name = "pers_clie")
@NamedEntityGraph(name = "persClie.Graph", attributeNodes = {
@NamedAttributeNode(value = "clieGrup"), 		
@NamedAttributeNode(value = "dimm") })
public class PersClie implements java.io.Serializable {

	private Integer personaId;
	private ClieGrup clieGrup;
	private Dimm dimm;
	private PersClie persClie;
	private Persona persona;
	private String razonSoci;
	private String natura;
	private BigDecimal descueMaxi;
	private boolean exonerIva;
	private boolean retienRent;
	private boolean retienIva;
	private short corteCred;
	private BigDecimal cupo;
	private String nota;
	private boolean estado;
	private Set<Egreso> egresos = new HashSet<Egreso>(0);
	private Set<PersClie> persClies = new HashSet<PersClie>(0);

	private static final long serialVersionUID = 5613232668933125501L;

	public PersClie() {
	}

	public PersClie(ClieGrup clieGrup, Dimm dimm, Persona persona, String natura, boolean exonerIva, boolean retienRent,
			BigDecimal descueMaxi, boolean retienIva, short corteCred, BigDecimal cupo, boolean estado) {
		this.clieGrup = clieGrup;
		this.dimm = dimm;
		this.persona = persona;
		this.natura = natura;
		this.descueMaxi = descueMaxi;
		this.exonerIva = exonerIva;
		this.retienRent = retienRent;
		this.retienIva = retienIva;
		this.corteCred = corteCred;
		this.cupo = cupo;
		this.estado = estado;
	}

	public PersClie(ClieGrup clieGrup, Dimm dimm, PersClie persClie, Persona persona, String natura, String razonSoci,
			BigDecimal descueMaxi, boolean exonerIva, boolean retienRent, boolean retienIva, short corteCred, BigDecimal cupo, String nota,
			boolean estado, Set<Egreso> egresos, Set<PersClie> persClies) {
		this.clieGrup = clieGrup;
		this.dimm = dimm;
		this.persClie = persClie;
		this.persona = persona;
		this.razonSoci = razonSoci;
		this.natura = natura;
		this.descueMaxi = descueMaxi;
		this.exonerIva = exonerIva;
		this.retienRent = retienRent;
		this.retienIva = retienIva;
		this.corteCred = corteCred;
		this.cupo = cupo;
		this.nota = nota;
		this.estado = estado;
		this.egresos = egresos;
		this.persClies = persClies;
	}

	@Id
	@GenericGenerator(name = "idPersClie", strategy = "foreign", parameters = @Parameter(name = "property", value = "persona"))
	@GeneratedValue(generator = "idPersClie")
	// @TableGenerator(name = "idPersClie", table = "Secuencial", pkColumnName =
	// "secuencial_id", pkColumnValue = "38", valueColumnName = "numero",
	// allocationSize = 1)
	// @GeneratedValue(strategy = GenerationType.TABLE, generator =
	// "idPersClie")
	@Column(name = "PERSONA_ID", unique = true, nullable = false)
	public Integer getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(Integer personaId) {
		this.personaId = personaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIE_GRUP_ID", nullable = false)
	public ClieGrup getClieGrup() {
		return this.clieGrup;
	}

	public void setClieGrup(ClieGrup clieGrup) {
		this.clieGrup = clieGrup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIMM_ID", nullable = false)
	public Dimm getDimm() {
		return this.dimm;
	}

	public void setDimm(Dimm dimm) {
		this.dimm = dimm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERSONA_SUPE_ID")
	public PersClie getPersClie() {
		return this.persClie;
	}

	public void setPersClie(PersClie persClie) {
		this.persClie = persClie;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.MERGE)
	@PrimaryKeyJoinColumn
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "RAZON_SOCI", length = 100)
	public String getRazonSoci() {
		return this.razonSoci;
	}

	public void setRazonSoci(String razonSoci) {
		this.razonSoci = razonSoci;
	}

	@Column(name = "NATURA", length = 02)
	public String getNatura() {
		return natura;
	}

	public void setNatura(String natura) {
		this.natura = natura;
	}

	@Min(0)
	@Max(100)
	@Column(name = "DESCUE_MAXI", nullable = false, precision = 8, scale = 4)
	public BigDecimal getDescueMaxi() {
		return descueMaxi;
	}

	public void setDescueMaxi(BigDecimal descueMaxi) {
		this.descueMaxi = descueMaxi;
	}

	@Column(name = "EXONER_IVA", nullable = false)
	public boolean isExonerIva() {
		return this.exonerIva;
	}

	public void setExonerIva(boolean exonerIva) {
		this.exonerIva = exonerIva;
	}

	@Column(name = "RETIEN_RENT", nullable = false)
	public boolean isRetienRent() {
		return this.retienRent;
	}

	public void setRetienRent(boolean retienRent) {
		this.retienRent = retienRent;
	}

	@Column(name = "RETIEN_IVA", nullable = false)
	public boolean isRetienIva() {
		return this.retienIva;
	}

	public void setRetienIva(boolean retienIva) {
		this.retienIva = retienIva;
	}

	@Column(name = "CORTE_CRED", nullable = false)
	public short getCorteCred() {
		return this.corteCred;
	}

	public void setCorteCred(short corteCred) {
		this.corteCred = corteCred;
	}

	@Column(name = "CUPO", nullable = false, precision = 12, scale = 6)
	public BigDecimal getCupo() {
		return this.cupo;
	}

	public void setCupo(BigDecimal cupo) {
		this.cupo = cupo;
	}

	@Column(name = "NOTA")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "ESTADO", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persClie")
	public Set<Egreso> getEgresos() {
		return this.egresos;
	}

	public void setEgresos(Set<Egreso> egresos) {
		this.egresos = egresos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persClie")
	public Set<PersClie> getPersClies() {
		return this.persClies;
	}

	public void setPersClies(Set<PersClie> persClies) {
		this.persClies = persClies;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((personaId == null) ? 0 : personaId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PersClie other = (PersClie) obj;
		if (personaId == null) {
			if (other.personaId != null)
				return false;
		} else if (!personaId.equals(other.personaId))
			return false;
		return true;
	}
}
