package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * AsisRegi generated by hbm2java
 */
@Entity
@Table(name = "asis_regi")
public class AsisRegi implements java.io.Serializable {

	private Integer asisRegiId;
	private Dispositivo dispositivo;
	private String codigoDisp;
	private String codigoEmpl;
	private String codigoTecla;
	private Date fechaDesc;
	private Date fechaHora;
	private String latitud;
	private String longitud;
	private String tipoRegi;
	private String estado;
	private Set<AsisHora> asisHoras = new HashSet<AsisHora>(0);

	private static final long serialVersionUID = -8507506602165850703L;

	public AsisRegi() {
	}

	public AsisRegi(Integer asisRegiId, String codigoDisp, String codigoEmpl,
			String codigoTecla, Date fechaDesc, Date fechaHora, String latitud,
			String longitud, String tipoRegi, String estado) {
		this.asisRegiId = asisRegiId;
		this.codigoDisp = codigoDisp;
		this.codigoEmpl = codigoEmpl;
		this.codigoTecla = codigoTecla;
		this.fechaDesc = fechaDesc;
		this.fechaHora = fechaHora;
		this.latitud = latitud;
		this.longitud = longitud;
		this.tipoRegi = tipoRegi;
		this.estado = estado;
	}

	public AsisRegi(Integer asisRegiId, Dispositivo dispositivo,
			String codigoDisp, String codigoEmpl, String codigoTecla,
			Date fechaDesc, Date fechaHora, String latitud, String longitud,
			String tipoRegi, String estado, Set<AsisHora> asisHoras) {
		this.asisRegiId = asisRegiId;
		this.dispositivo = dispositivo;
		this.codigoDisp = codigoDisp;
		this.codigoEmpl = codigoEmpl;
		this.codigoTecla = codigoTecla;
		this.fechaDesc = fechaDesc;
		this.fechaHora = fechaHora;
		this.latitud = latitud;
		this.longitud = longitud;
		this.tipoRegi = tipoRegi;
		this.estado = estado;
		this.asisHoras = asisHoras;
	}

	@Id
	@TableGenerator(name = "idAsisRegi", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "asis_regi", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAsisRegi")
	@Column(name = "asis_regi_id", unique = true, nullable = false)
	public Integer getAsisRegiId() {
		return this.asisRegiId;
	}

	public void setAsisRegiId(Integer asisRegiId) {
		this.asisRegiId = asisRegiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dispositivo_id")
	public Dispositivo getDispositivo() {
		return this.dispositivo;
	}

	public void setDispositivo(Dispositivo dispositivo) {
		this.dispositivo = dispositivo;
	}

	@Column(name = "codigo_disp", nullable = false, length = 12)
	public String getCodigoDisp() {
		return this.codigoDisp;
	}

	public void setCodigoDisp(String codigoDisp) {
		this.codigoDisp = codigoDisp;
	}

	@Column(name = "codigo_empl", nullable = false, length = 32)
	public String getCodigoEmpl() {
		return this.codigoEmpl;
	}

	public void setCodigoEmpl(String codigoEmpl) {
		this.codigoEmpl = codigoEmpl;
	}

	@Column(name = "codigo_tecla", nullable = false, length = 12)
	public String getCodigoTecla() {
		return this.codigoTecla;
	}

	public void setCodigoTecla(String codigoTecla) {
		this.codigoTecla = codigoTecla;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desc", nullable = false, length = 29)
	public Date getFechaDesc() {
		return this.fechaDesc;
	}

	public void setFechaDesc(Date fechaDesc) {
		this.fechaDesc = fechaDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 29)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "latitud", nullable = false, length = 100)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 100)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@Column(name = "tipo_regi", nullable = false, length = 12)
	public String getTipoRegi() {
		return this.tipoRegi;
	}

	public void setTipoRegi(String tipoRegi) {
		this.tipoRegi = tipoRegi;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asisRegi")
	public Set<AsisHora> getAsisHoras() {
		return this.asisHoras;
	}

	public void setAsisHoras(Set<AsisHora> asisHoras) {
		this.asisHoras = asisHoras;
	}

}
