package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * AuseRecu generated by hbm2java
 */
@Entity
@Table(name = "ause_recu")
public class AuseRecu implements java.io.Serializable {

	private Integer auseRecuId;
	private Ausencia ausencia;
	private Date fechaDesd;
	private Date fechaHast;
	private Date horaDes;
	private Date horaHast;

	private static final long serialVersionUID = -538955694463507702L;

	public AuseRecu() {
	}

	public AuseRecu(Integer auseRecuId, Ausencia ausencia, Date fechaDesd,
			Date fechaHast, Date horaDes, Date horaHast) {
		this.auseRecuId = auseRecuId;
		this.ausencia = ausencia;
		this.fechaDesd = fechaDesd;
		this.fechaHast = fechaHast;
		this.horaDes = horaDes;
		this.horaHast = horaHast;
	}

	@Id
	@TableGenerator(name = "idAuseRecu", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "ause_recu", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idAuseRecu")
	@Column(name = "ause_recu_id", unique = true, nullable = false)
	public Integer getAuseRecuId() {
		return this.auseRecuId;
	}

	public void setAuseRecuId(Integer auseRecuId) {
		this.auseRecuId = auseRecuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ausencia_id", nullable = false)
	public Ausencia getAusencia() {
		return this.ausencia;
	}

	public void setAusencia(Ausencia ausencia) {
		this.ausencia = ausencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_desd", nullable = false, length = 29)
	public Date getFechaDesd() {
		return this.fechaDesd;
	}

	public void setFechaDesd(Date fechaDesd) {
		this.fechaDesd = fechaDesd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hast", nullable = false, length = 29)
	public Date getFechaHast() {
		return this.fechaHast;
	}

	public void setFechaHast(Date fechaHast) {
		this.fechaHast = fechaHast;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_des", nullable = false, length = 29)
	public Date getHoraDes() {
		return this.horaDes;
	}

	public void setHoraDes(Date horaDes) {
		this.horaDes = horaDes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_hast", nullable = false, length = 29)
	public Date getHoraHast() {
		return this.horaHast;
	}

	public void setHoraHast(Date horaHast) {
		this.horaHast = horaHast;
	}

}
