package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * DepaNive generated by hbm2java
 */
@Entity
@Table(name = "depa_nive")
public class DepaNive implements java.io.Serializable {

	private Integer depaNiveId;
	private String descri;
	private Integer nivel;
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);

	private static final long serialVersionUID = 2000711775376409286L;

	public DepaNive() {
	}

	public DepaNive(Integer depaNiveId, String descri, Integer nivel) {
		this.depaNiveId = depaNiveId;
		this.descri = descri;
		this.nivel = nivel;
	}

	public DepaNive(Integer depaNiveId, String descri, Integer nivel,
			Set<Departamento> departamentos) {
		this.depaNiveId = depaNiveId;
		this.descri = descri;
		this.nivel = nivel;
		this.departamentos = departamentos;
	}

	@Id
	@TableGenerator(name = "idDepaNive", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "depa_nive", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idDepaNive")
	@Column(name = "depa_nive_id", unique = true, nullable = false)
	public Integer getDepaNiveId() {
		return this.depaNiveId;
	}

	public void setDepaNiveId(Integer depaNiveId) {
		this.depaNiveId = depaNiveId;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "nivel", nullable = false)
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "depaNive")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

}
