package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Dispositivo generated by hbm2java
 */
@Entity
@Table(name = "dispositivo")
public class Dispositivo implements java.io.Serializable {

	private Integer dispositivoId;
	private String codigo;
	private String descri;
	private String ip;
	private String mascar;
	private String puertaEnla;
	private String puerto;
	private String nota;
	private String estado;
	private Set<AsisRegi> asisRegis = new HashSet<AsisRegi>(0);

	private static final long serialVersionUID = -7427829677781700484L;

	public Dispositivo() {
	}

	public Dispositivo(Integer dispositivoId, String codigo, String descri,
			String ip, String estado) {
		this.dispositivoId = dispositivoId;
		this.codigo = codigo;
		this.descri = descri;
		this.ip = ip;
		this.estado = estado;
	}

	public Dispositivo(Integer dispositivoId, String codigo, String descri,
			String ip, String mascar, String puertaEnla, String puerto,
			String nota, String estado, Set<AsisRegi> asisRegis) {
		this.dispositivoId = dispositivoId;
		this.codigo = codigo;
		this.descri = descri;
		this.ip = ip;
		this.mascar = mascar;
		this.puertaEnla = puertaEnla;
		this.puerto = puerto;
		this.nota = nota;
		this.estado = estado;
		this.asisRegis = asisRegis;
	}

	@Id
	@TableGenerator(name = "idDispositivo", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "dispositivo", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idDispositivo")
	@Column(name = "dispositivo_id", unique = true, nullable = false)
	public Integer getDispositivoId() {
		return this.dispositivoId;
	}

	public void setDispositivoId(Integer dispositivoId) {
		this.dispositivoId = dispositivoId;
	}

	@Column(name = "codigo", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "ip", nullable = false, length = 32)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "mascar", length = 32)
	public String getMascar() {
		return this.mascar;
	}

	public void setMascar(String mascar) {
		this.mascar = mascar;
	}

	@Column(name = "puerta_enla", length = 32)
	public String getPuertaEnla() {
		return this.puertaEnla;
	}

	public void setPuertaEnla(String puertaEnla) {
		this.puertaEnla = puertaEnla;
	}

	@Column(name = "puerto", length = 32)
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	@Column(name = "nota")
	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dispositivo")
	public Set<AsisRegi> getAsisRegis() {
		return this.asisRegis;
	}

	public void setAsisRegis(Set<AsisRegi> asisRegis) {
		this.asisRegis = asisRegis;
	}

}
