package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import ec.com.tecnointel.soem.parametro.modelo.Documento;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;

/**
 * DocuAuse generated by hbm2java
 */
@Entity
@Table(name = "docu_ause")
public class DocuAuse implements java.io.Serializable {

	private Integer documentoId;
	private Documento documento;
	private Integer maximoDias;
	private Integer maximoHora;
	private boolean acumulDiasEnfe;
	private boolean acumulDiasMate;
	private BigDecimal sueldoPorc;
	private BigDecimal diasPago;
	private Integer diasSoli;
	private Integer diasAuto;
	private Integer diasAdjuDocu;
	private String cargo;
	private boolean recorrFechVaca;
	private boolean recurs;
	private boolean creaAcciPers;
	private boolean notifiCorrSoli;
	private boolean notifiCorrActu;
	private boolean notifiCorrElim;
	private boolean notifiCorrAuto;
	private boolean notifiCorrLegal;
	private boolean notifiCeluSoli;
	private boolean notifiCeluActu;
	private boolean notifiCeluElim;
	private boolean notifiCeluAuto;
	private boolean notifiCeluLegal;
	private String estado;
	private Set<Ausencia> ausencias = new HashSet<Ausencia>(0);

	private static final long serialVersionUID = 8519658751021959571L;

	public DocuAuse() {
	}

	public DocuAuse(Documento documento, Integer maximoDias,
			Integer maximoHora, boolean acumulDiasEnfe, boolean acumulDiasMate,
			BigDecimal sueldoPorc, BigDecimal diasPago, Integer diasSoli,
			Integer diasAuto, Integer diasAdjuDocu, String cargo,
			boolean recorrFechVaca, boolean recurs, boolean creaAcciPers,
			boolean notifiCorrSoli, boolean notifiCorrActu,
			boolean notifiCorrElim, boolean notifiCorrAuto,
			boolean notifiCorrLegal, boolean notifiCeluSoli,
			boolean notifiCeluActu, boolean notifiCeluElim,
			boolean notifiCeluAuto, boolean notifiCeluLegal, String estado) {
		this.documento = documento;
		this.maximoDias = maximoDias;
		this.maximoHora = maximoHora;
		this.acumulDiasEnfe = acumulDiasEnfe;
		this.acumulDiasMate = acumulDiasMate;
		this.sueldoPorc = sueldoPorc;
		this.diasPago = diasPago;
		this.diasSoli = diasSoli;
		this.diasAuto = diasAuto;
		this.diasAdjuDocu = diasAdjuDocu;
		this.cargo = cargo;
		this.recorrFechVaca = recorrFechVaca;
		this.recurs = recurs;
		this.creaAcciPers = creaAcciPers;
		this.notifiCorrSoli = notifiCorrSoli;
		this.notifiCorrActu = notifiCorrActu;
		this.notifiCorrElim = notifiCorrElim;
		this.notifiCorrAuto = notifiCorrAuto;
		this.notifiCorrLegal = notifiCorrLegal;
		this.notifiCeluSoli = notifiCeluSoli;
		this.notifiCeluActu = notifiCeluActu;
		this.notifiCeluElim = notifiCeluElim;
		this.notifiCeluAuto = notifiCeluAuto;
		this.notifiCeluLegal = notifiCeluLegal;
		this.estado = estado;
	}

	public DocuAuse(Documento documento, Integer maximoDias,
			Integer maximoHora, boolean acumulDiasEnfe, boolean acumulDiasMate,
			BigDecimal sueldoPorc, BigDecimal diasPago, Integer diasSoli,
			Integer diasAuto, Integer diasAdjuDocu, String cargo,
			boolean recorrFechVaca, boolean recurs, boolean creaAcciPers,
			boolean notifiCorrSoli, boolean notifiCorrActu,
			boolean notifiCorrElim, boolean notifiCorrAuto,
			boolean notifiCorrLegal, boolean notifiCeluSoli,
			boolean notifiCeluActu, boolean notifiCeluElim,
			boolean notifiCeluAuto, boolean notifiCeluLegal, String estado,
			Set<Ausencia> ausencias) {
		this.documento = documento;
		this.maximoDias = maximoDias;
		this.maximoHora = maximoHora;
		this.acumulDiasEnfe = acumulDiasEnfe;
		this.acumulDiasMate = acumulDiasMate;
		this.sueldoPorc = sueldoPorc;
		this.diasPago = diasPago;
		this.diasSoli = diasSoli;
		this.diasAuto = diasAuto;
		this.diasAdjuDocu = diasAdjuDocu;
		this.cargo = cargo;
		this.recorrFechVaca = recorrFechVaca;
		this.recurs = recurs;
		this.creaAcciPers = creaAcciPers;
		this.notifiCorrSoli = notifiCorrSoli;
		this.notifiCorrActu = notifiCorrActu;
		this.notifiCorrElim = notifiCorrElim;
		this.notifiCorrAuto = notifiCorrAuto;
		this.notifiCorrLegal = notifiCorrLegal;
		this.notifiCeluSoli = notifiCeluSoli;
		this.notifiCeluActu = notifiCeluActu;
		this.notifiCeluElim = notifiCeluElim;
		this.notifiCeluAuto = notifiCeluAuto;
		this.notifiCeluLegal = notifiCeluLegal;
		this.estado = estado;
		this.ausencias = ausencias;
	}

	@Id
	@GenericGenerator(name = "idDocuAuse", strategy = "foreign", parameters = @Parameter(name = "property", value = "documento"))
	@GeneratedValue(generator = "idDocuAuse")
	@Column(name = "documento_id", unique = true, nullable = false)
	public Integer getDocumentoId() {
		return this.documentoId;
	}

	public void setDocumentoId(Integer documentoId) {
		this.documentoId = documentoId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	@Column(name = "maximo_dias", nullable = false)
	public Integer getMaximoDias() {
		return this.maximoDias;
	}

	public void setMaximoDias(Integer maximoDias) {
		this.maximoDias = maximoDias;
	}

	@Column(name = "maximo_hora", nullable = false)
	public Integer getMaximoHora() {
		return this.maximoHora;
	}

	public void setMaximoHora(Integer maximoHora) {
		this.maximoHora = maximoHora;
	}

	@Column(name = "acumul_dias_enfe", nullable = false)
	public boolean isAcumulDiasEnfe() {
		return this.acumulDiasEnfe;
	}

	public void setAcumulDiasEnfe(boolean acumulDiasEnfe) {
		this.acumulDiasEnfe = acumulDiasEnfe;
	}

	@Column(name = "acumul_dias_mate", nullable = false)
	public boolean isAcumulDiasMate() {
		return this.acumulDiasMate;
	}

	public void setAcumulDiasMate(boolean acumulDiasMate) {
		this.acumulDiasMate = acumulDiasMate;
	}

	@Column(name = "sueldo_porc", nullable = false, precision = 8, scale = 4)
	public BigDecimal getSueldoPorc() {
		return this.sueldoPorc;
	}

	public void setSueldoPorc(BigDecimal sueldoPorc) {
		this.sueldoPorc = sueldoPorc;
	}

	@Column(name = "dias_pago", nullable = false, precision = 6)
	public BigDecimal getDiasPago() {
		return this.diasPago;
	}

	public void setDiasPago(BigDecimal diasPago) {
		this.diasPago = diasPago;
	}

	@Column(name = "dias_soli", nullable = false)
	public Integer getDiasSoli() {
		return this.diasSoli;
	}

	public void setDiasSoli(Integer diasSoli) {
		this.diasSoli = diasSoli;
	}

	@Column(name = "dias_auto", nullable = false)
	public Integer getDiasAuto() {
		return this.diasAuto;
	}

	public void setDiasAuto(Integer diasAuto) {
		this.diasAuto = diasAuto;
	}

	@Column(name = "dias_adju_docu", nullable = false)
	public Integer getDiasAdjuDocu() {
		return this.diasAdjuDocu;
	}

	public void setDiasAdjuDocu(Integer diasAdjuDocu) {
		this.diasAdjuDocu = diasAdjuDocu;
	}

	@Column(name = "cargo", nullable = false, length = 12)
	public String getCargo() {
		return this.cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	@Column(name = "recorr_fech_vaca", nullable = false)
	public boolean isRecorrFechVaca() {
		return this.recorrFechVaca;
	}

	public void setRecorrFechVaca(boolean recorrFechVaca) {
		this.recorrFechVaca = recorrFechVaca;
	}

	@Column(name = "recurs", nullable = false)
	public boolean isRecurs() {
		return this.recurs;
	}

	public void setRecurs(boolean recurs) {
		this.recurs = recurs;
	}

	@Column(name = "crea_acci_pers", nullable = false)
	public boolean isCreaAcciPers() {
		return this.creaAcciPers;
	}

	public void setCreaAcciPers(boolean creaAcciPers) {
		this.creaAcciPers = creaAcciPers;
	}

	@Column(name = "notifi_corr_soli", nullable = false)
	public boolean isNotifiCorrSoli() {
		return this.notifiCorrSoli;
	}

	public void setNotifiCorrSoli(boolean notifiCorrSoli) {
		this.notifiCorrSoli = notifiCorrSoli;
	}

	@Column(name = "notifi_corr_actu", nullable = false)
	public boolean isNotifiCorrActu() {
		return this.notifiCorrActu;
	}

	public void setNotifiCorrActu(boolean notifiCorrActu) {
		this.notifiCorrActu = notifiCorrActu;
	}

	@Column(name = "notifi_corr_elim", nullable = false)
	public boolean isNotifiCorrElim() {
		return this.notifiCorrElim;
	}

	public void setNotifiCorrElim(boolean notifiCorrElim) {
		this.notifiCorrElim = notifiCorrElim;
	}

	@Column(name = "notifi_corr_auto", nullable = false)
	public boolean isNotifiCorrAuto() {
		return this.notifiCorrAuto;
	}

	public void setNotifiCorrAuto(boolean notifiCorrAuto) {
		this.notifiCorrAuto = notifiCorrAuto;
	}

	@Column(name = "notifi_corr_legal", nullable = false)
	public boolean isNotifiCorrLegal() {
		return this.notifiCorrLegal;
	}

	public void setNotifiCorrLegal(boolean notifiCorrLegal) {
		this.notifiCorrLegal = notifiCorrLegal;
	}

	@Column(name = "notifi_celu_soli", nullable = false)
	public boolean isNotifiCeluSoli() {
		return this.notifiCeluSoli;
	}

	public void setNotifiCeluSoli(boolean notifiCeluSoli) {
		this.notifiCeluSoli = notifiCeluSoli;
	}

	@Column(name = "notifi_celu_actu", nullable = false)
	public boolean isNotifiCeluActu() {
		return this.notifiCeluActu;
	}

	public void setNotifiCeluActu(boolean notifiCeluActu) {
		this.notifiCeluActu = notifiCeluActu;
	}

	@Column(name = "notifi_celu_elim", nullable = false)
	public boolean isNotifiCeluElim() {
		return this.notifiCeluElim;
	}

	public void setNotifiCeluElim(boolean notifiCeluElim) {
		this.notifiCeluElim = notifiCeluElim;
	}

	@Column(name = "notifi_celu_auto", nullable = false)
	public boolean isNotifiCeluAuto() {
		return this.notifiCeluAuto;
	}

	public void setNotifiCeluAuto(boolean notifiCeluAuto) {
		this.notifiCeluAuto = notifiCeluAuto;
	}

	@Column(name = "notifi_celu_legal", nullable = false)
	public boolean isNotifiCeluLegal() {
		return this.notifiCeluLegal;
	}

	public void setNotifiCeluLegal(boolean notifiCeluLegal) {
		this.notifiCeluLegal = notifiCeluLegal;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docuAuse")
	public Set<Ausencia> getAusencias() {
		return this.ausencias;
	}

	public void setAusencias(Set<Ausencia> ausencias) {
		this.ausencias = ausencias;
	}

}
