package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * EmplCargVaca generated by hbm2java
 */
@Entity
@Table(name = "empl_carg_vaca")
public class EmplCargVaca implements java.io.Serializable {

	private Integer emplCargVacaId;
	private PersEmpl persEmpl;
	private Date fecha;
	private BigDecimal dias;
	private BigDecimal diasIncr;
	private Set<KardVaca> kardVacas = new HashSet<KardVaca>(0);

	private static final long serialVersionUID = 3365734639431115952L;

	public EmplCargVaca() {
	}

	public EmplCargVaca(Integer emplCargVacaId, PersEmpl persEmpl, Date fecha,
			BigDecimal dias, BigDecimal diasIncr) {
		this.emplCargVacaId = emplCargVacaId;
		this.persEmpl = persEmpl;
		this.fecha = fecha;
		this.dias = dias;
		this.diasIncr = diasIncr;
	}

	public EmplCargVaca(Integer emplCargVacaId, PersEmpl persEmpl, Date fecha,
			BigDecimal dias, BigDecimal diasIncr, Set<KardVaca> kardVacas) {
		this.emplCargVacaId = emplCargVacaId;
		this.persEmpl = persEmpl;
		this.fecha = fecha;
		this.dias = dias;
		this.diasIncr = diasIncr;
		this.kardVacas = kardVacas;
	}

	@Id
	@TableGenerator(name = "idEmplCargVaca", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_carg_vaca", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplCargVaca")
	@Column(name = "empl_carg_vaca_id", unique = true, nullable = false)
	public Integer getEmplCargVacaId() {
		return this.emplCargVacaId;
	}

	public void setEmplCargVacaId(Integer emplCargVacaId) {
		this.emplCargVacaId = emplCargVacaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "dias", nullable = false, precision = 8, scale = 4)
	public BigDecimal getDias() {
		return this.dias;
	}

	public void setDias(BigDecimal dias) {
		this.dias = dias;
	}

	@Column(name = "dias_incr", nullable = false, precision = 8, scale = 4)
	public BigDecimal getDiasIncr() {
		return this.diasIncr;
	}

	public void setDiasIncr(BigDecimal diasIncr) {
		this.diasIncr = diasIncr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emplCargVaca")
	public Set<KardVaca> getKardVacas() {
		return this.kardVacas;
	}

	public void setKardVacas(Set<KardVaca> kardVacas) {
		this.kardVacas = kardVacas;
	}

}
