package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * EmplCont generated by hbm2java
 */
@Entity
@Table(name = "empl_cont")
public class EmplCont implements java.io.Serializable {

	private Integer emplContId;
	private PersEmpl persEmpl;
	private String descri;
	private String tipo;
	private String telefo;
	private String correo;
	private Date fechaNaci;
	private String discapTipo;
	private BigDecimal discapPorc;
	private String discapCarn;

	private static final long serialVersionUID = 5078388741566486534L;

	public EmplCont() {
	}

	public EmplCont(Integer emplContId, PersEmpl persEmpl, String descri,
			String tipo, String telefo) {
		this.emplContId = emplContId;
		this.persEmpl = persEmpl;
		this.descri = descri;
		this.tipo = tipo;
		this.telefo = telefo;
	}

	public EmplCont(Integer emplContId, PersEmpl persEmpl, String descri,
			String tipo, String telefo, String correo, Date fechaNaci,
			String discapTipo, BigDecimal discapPorc, String discapCarn) {
		this.emplContId = emplContId;
		this.persEmpl = persEmpl;
		this.descri = descri;
		this.tipo = tipo;
		this.telefo = telefo;
		this.correo = correo;
		this.fechaNaci = fechaNaci;
		this.discapTipo = discapTipo;
		this.discapPorc = discapPorc;
		this.discapCarn = discapCarn;
	}

	@Id
	@TableGenerator(name = "idEmplCont", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_cont", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplCont")
	@Column(name = "empl_cont_id", unique = true, nullable = false)
	public Integer getEmplContId() {
		return this.emplContId;
	}

	public void setEmplContId(Integer emplContId) {
		this.emplContId = emplContId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "tipo", nullable = false, length = 32)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "telefo", nullable = false, length = 30)
	public String getTelefo() {
		return this.telefo;
	}

	public void setTelefo(String telefo) {
		this.telefo = telefo;
	}

	@Column(name = "correo", length = 100)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_naci", length = 13)
	public Date getFechaNaci() {
		return this.fechaNaci;
	}

	public void setFechaNaci(Date fechaNaci) {
		this.fechaNaci = fechaNaci;
	}

	@Column(name = "discap_tipo", length = 32)
	public String getDiscapTipo() {
		return this.discapTipo;
	}

	public void setDiscapTipo(String discapTipo) {
		this.discapTipo = discapTipo;
	}

	@Column(name = "discap_porc", precision = 8, scale = 4)
	public BigDecimal getDiscapPorc() {
		return this.discapPorc;
	}

	public void setDiscapPorc(BigDecimal discapPorc) {
		this.discapPorc = discapPorc;
	}

	@Column(name = "discap_carn", length = 32)
	public String getDiscapCarn() {
		return this.discapCarn;
	}

	public void setDiscapCarn(String discapCarn) {
		this.discapCarn = discapCarn;
	}

}
