package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * EmplDisc generated by hbm2java
 */
@Entity
@Table(name = "empl_disc")
public class EmplDisc implements java.io.Serializable {

	private Integer emplDiscId;
	private PersEmpl persEmpl;
	private String tipo;
	private BigDecimal porcen;
	private String carnet;

	private static final long serialVersionUID = -7401254385550053025L;

	public EmplDisc() {
	}

	public EmplDisc(Integer emplDiscId, PersEmpl persEmpl, String tipo,
			BigDecimal porcen, String carnet) {
		this.emplDiscId = emplDiscId;
		this.persEmpl = persEmpl;
		this.tipo = tipo;
		this.porcen = porcen;
		this.carnet = carnet;
	}

	@Id
	@TableGenerator(name = "idEmplDisc", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_disc", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplDisc")
	@Column(name = "empl_disc_id", unique = true, nullable = false)
	public Integer getEmplDiscId() {
		return this.emplDiscId;
	}

	public void setEmplDiscId(Integer emplDiscId) {
		this.emplDiscId = emplDiscId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Column(name = "tipo", nullable = false, length = 32)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "porcen", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPorcen() {
		return this.porcen;
	}

	public void setPorcen(BigDecimal porcen) {
		this.porcen = porcen;
	}

	@Column(name = "carnet", nullable = false, length = 32)
	public String getCarnet() {
		return this.carnet;
	}

	public void setCarnet(String carnet) {
		this.carnet = carnet;
	}

}
