package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * EmplHora generated by hbm2java
 */
@Entity
@Table(name = "empl_hora")
public class EmplHora implements java.io.Serializable {

	private Integer emplHoraId;
	private String codigo;
	private Integer numero;
	private Date fechaDesd;
	private Date fechaHast;
	private Set<EmplHoraDeta> emplHoraDetas = new HashSet<EmplHoraDeta>(0);

	private static final long serialVersionUID = 5475073767952439133L;

	public EmplHora() {
	}

	public EmplHora(Integer emplHoraId, String codigo, Integer numero,
			Date fechaDesd, Date fechaHast) {
		this.emplHoraId = emplHoraId;
		this.codigo = codigo;
		this.numero = numero;
		this.fechaDesd = fechaDesd;
		this.fechaHast = fechaHast;
	}

	public EmplHora(Integer emplHoraId, String codigo, Integer numero,
			Date fechaDesd, Date fechaHast, Set<EmplHoraDeta> emplHoraDetas) {
		this.emplHoraId = emplHoraId;
		this.codigo = codigo;
		this.numero = numero;
		this.fechaDesd = fechaDesd;
		this.fechaHast = fechaHast;
		this.emplHoraDetas = emplHoraDetas;
	}

	@Id
	@TableGenerator(name = "idEmplHora", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_hora", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplHora")
	@Column(name = "empl_hora_id", unique = true, nullable = false)
	public Integer getEmplHoraId() {
		return this.emplHoraId;
	}

	public void setEmplHoraId(Integer emplHoraId) {
		this.emplHoraId = emplHoraId;
	}

	@Column(name = "codigo", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "numero", nullable = false)
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_desd", nullable = false, length = 13)
	public Date getFechaDesd() {
		return this.fechaDesd;
	}

	public void setFechaDesd(Date fechaDesd) {
		this.fechaDesd = fechaDesd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_hast", nullable = false, length = 13)
	public Date getFechaHast() {
		return this.fechaHast;
	}

	public void setFechaHast(Date fechaHast) {
		this.fechaHast = fechaHast;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emplHora")
	public Set<EmplHoraDeta> getEmplHoraDetas() {
		return this.emplHoraDetas;
	}

	public void setEmplHoraDetas(Set<EmplHoraDeta> emplHoraDetas) {
		this.emplHoraDetas = emplHoraDetas;
	}

}
