package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * EmplTitu generated by hbm2java
 */
@Entity
@Table(name = "empl_titu")
public class EmplTitu implements java.io.Serializable {

	private Integer emplTituId;
	private PersEmpl persEmpl;
	private String descri;
	private String tipo;

	private static final long serialVersionUID = 5169490612015997647L;

	public EmplTitu() {
	}

	public EmplTitu(Integer emplTituId, PersEmpl persEmpl, String descri,
			String tipo) {
		this.emplTituId = emplTituId;
		this.persEmpl = persEmpl;
		this.descri = descri;
		this.tipo = tipo;
	}

	@Id
	@TableGenerator(name = "idEmplTitu", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "empl_titu", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idEmplTitu")
	@Column(name = "empl_titu_id", unique = true, nullable = false)
	public Integer getEmplTituId() {
		return this.emplTituId;
	}

	public void setEmplTituId(Integer emplTituId) {
		this.emplTituId = emplTituId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona_id", nullable = false)
	public PersEmpl getPersEmpl() {
		return this.persEmpl;
	}

	public void setPersEmpl(PersEmpl persEmpl) {
		this.persEmpl = persEmpl;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "tipo", nullable = false, length = 32)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
