package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Feriado generated by hbm2java
 */
@Entity
@Table(name = "feriado")
public class Feriado implements java.io.Serializable {

	private Integer feriadoId;
	private String descri;
	private Date fecha;
	private boolean recupe;
	private String estado;
	private Set<FeriRecu> feriRecus = new HashSet<FeriRecu>(0);
	private Set<FeriMapa> mapaFeris = new HashSet<FeriMapa>(0);

	private static final long serialVersionUID = -2920256668976662187L;

	public Feriado() {
	}

	public Feriado(Integer feriadoId, String descri, Date fecha, boolean recupe, String estado) {
		this.feriadoId = feriadoId;
		this.descri = descri;
		this.fecha = fecha;
		this.recupe = recupe;
		this.estado = estado;
	}

	public Feriado(Integer feriadoId, String descri, Date fecha, String estado,
			boolean recupe, Set<FeriRecu> feriRecus, Set<FeriMapa> mapaFeris) {
		this.feriadoId = feriadoId;
		this.descri = descri;
		this.fecha = fecha;
		this.recupe = recupe;
		this.feriRecus = feriRecus;
		this.mapaFeris = mapaFeris;
		this.estado = estado;
	}

	@Id
	@TableGenerator(name = "idFeriado", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "feriado", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idFeriado")
	@Column(name = "feriado_id", unique = true, nullable = false)
	public Integer getFeriadoId() {
		return this.feriadoId;
	}

	public void setFeriadoId(Integer feriadoId) {
		this.feriadoId = feriadoId;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "recupe", nullable = false)
	public boolean isRecupe() {
		return this.recupe;
	}

	public void setRecupe(boolean recupe) {
		this.recupe = recupe;
	}
	
	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feriado")
	public Set<FeriRecu> getFeriRecus() {
		return this.feriRecus;
	}

	public void setFeriRecus(Set<FeriRecu> feriRecus) {
		this.feriRecus = feriRecus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feriado")
	public Set<FeriMapa> getMapaFeris() {
		return this.mapaFeris;
	}

	public void setMapaFeris(Set<FeriMapa> mapaFeris) {
		this.mapaFeris = mapaFeris;
	}
}
