package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * HoraExtr generated by hbm2java
 */
@Entity
@Table(name = "hora_extr")
public class HoraExtr implements java.io.Serializable {

	private Integer horaExtrId;
	private String descri;
	private Date horaDesd;
	private Date horaHast;
	private BigDecimal porcen;
	private boolean diasLabo;
	private boolean diasLibr;
	private boolean diasFeri;
	private Integer maximoDia;
	private Integer maximoSema;
	private Integer maximoMes;

	private static final long serialVersionUID = 2725036416546016320L;

	public HoraExtr() {
	}

	public HoraExtr(Integer horaExtrId, String descri, Date horaDesd,
			Date horaHast, BigDecimal porcen, boolean diasLabo,
			boolean diasLibr, boolean diasFeri, Integer maximoDia,
			Integer maximoSema, Integer maximoMes) {
		this.horaExtrId = horaExtrId;
		this.descri = descri;
		this.horaDesd = horaDesd;
		this.horaHast = horaHast;
		this.porcen = porcen;
		this.diasLabo = diasLabo;
		this.diasLibr = diasLibr;
		this.diasFeri = diasFeri;
		this.maximoDia = maximoDia;
		this.maximoSema = maximoSema;
		this.maximoMes = maximoMes;
	}

	@Id
	@TableGenerator(name = "idHoraExtra", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "hora_extra", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idHoraExtra")
	@Column(name = "hora_extr_id", unique = true, nullable = false)
	public Integer getHoraExtrId() {
		return this.horaExtrId;
	}

	public void setHoraExtrId(Integer horaExtrId) {
		this.horaExtrId = horaExtrId;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_desd", nullable = false, length = 29)
	public Date getHoraDesd() {
		return this.horaDesd;
	}

	public void setHoraDesd(Date horaDesd) {
		this.horaDesd = horaDesd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hora_hast", nullable = false, length = 29)
	public Date getHoraHast() {
		return this.horaHast;
	}

	public void setHoraHast(Date horaHast) {
		this.horaHast = horaHast;
	}

	@Column(name = "porcen", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPorcen() {
		return this.porcen;
	}

	public void setPorcen(BigDecimal porcen) {
		this.porcen = porcen;
	}

	@Column(name = "dias_labo", nullable = false)
	public boolean isDiasLabo() {
		return this.diasLabo;
	}

	public void setDiasLabo(boolean diasLabo) {
		this.diasLabo = diasLabo;
	}

	@Column(name = "dias_libr", nullable = false)
	public boolean isDiasLibr() {
		return this.diasLibr;
	}

	public void setDiasLibr(boolean diasLibr) {
		this.diasLibr = diasLibr;
	}

	@Column(name = "dias_feri", nullable = false)
	public boolean isDiasFeri() {
		return this.diasFeri;
	}

	public void setDiasFeri(boolean diasFeri) {
		this.diasFeri = diasFeri;
	}

	@Column(name = "maximo_dia", nullable = false)
	public Integer getMaximoDia() {
		return this.maximoDia;
	}

	public void setMaximoDia(Integer maximoDia) {
		this.maximoDia = maximoDia;
	}

	@Column(name = "maximo_sema", nullable = false)
	public Integer getMaximoSema() {
		return this.maximoSema;
	}

	public void setMaximoSema(Integer maximoSema) {
		this.maximoSema = maximoSema;
	}

	@Column(name = "maximo_mes", nullable = false)
	public Integer getMaximoMes() {
		return this.maximoMes;
	}

	public void setMaximoMes(Integer maximoMes) {
		this.maximoMes = maximoMes;
	}

}
