package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * HoraPlan generated by hbm2java
 */
@Entity
@Table(name = "hora_plan")
public class HoraPlan implements java.io.Serializable {

	private Integer horaPlanId;
	private String descri;
	private Set<EmplHoraPlan> emplHoraPlans = new HashSet<EmplHoraPlan>(0);
	private Set<HoraPlanDeta> horaPlanDetas = new HashSet<HoraPlanDeta>(0);

	private static final long serialVersionUID = -4513585182504154160L;

	public HoraPlan() {
	}

	public HoraPlan(Integer horaPlanId, String descri) {
		this.horaPlanId = horaPlanId;
		this.descri = descri;
	}

	public HoraPlan(Integer horaPlanId, String descri,
			Set<EmplHoraPlan> emplHoraPlans, Set<HoraPlanDeta> horaPlanDetas) {
		this.horaPlanId = horaPlanId;
		this.descri = descri;
		this.emplHoraPlans = emplHoraPlans;
		this.horaPlanDetas = horaPlanDetas;
	}

	@Id
	@TableGenerator(name = "idHoraPlan", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "hora_plan", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idHoraPlan")
	@Column(name = "hora_plan_id", unique = true, nullable = false)
	public Integer getHoraPlanId() {
		return this.horaPlanId;
	}

	public void setHoraPlanId(Integer horaPlanId) {
		this.horaPlanId = horaPlanId;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horaPlan")
	public Set<EmplHoraPlan> getEmplHoraPlans() {
		return this.emplHoraPlans;
	}

	public void setEmplHoraPlans(Set<EmplHoraPlan> emplHoraPlans) {
		this.emplHoraPlans = emplHoraPlans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horaPlan")
	public Set<HoraPlanDeta> getHoraPlanDetas() {
		return this.horaPlanDetas;
	}

	public void setHoraPlanDetas(Set<HoraPlanDeta> horaPlanDetas) {
		this.horaPlanDetas = horaPlanDetas;
	}

}
