package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "horario")
public class Horario implements java.io.Serializable {

	private Integer horarioId;
	private String codigo;
	private String descri;
	private Integer minutoAlim;
	private Integer horasLabo;
	private String tipo;
	private Integer inicioExtr;
	private String estado;
	private Set<HoraDeta> horaDetas = new HashSet<HoraDeta>(0);
	private Set<EmplHoraDeta> emplHoraDetas = new HashSet<EmplHoraDeta>(0);
	private Set<HoraPlanDeta> horaPlanDetas = new HashSet<HoraPlanDeta>(0);

	private static final long serialVersionUID = -4470037441315870445L;

	public Horario() {
	}

	public Horario(Integer horarioId, String codigo, String descri,
			Integer minutoAlim, Integer horasLabo, String tipo,
			Integer inicioExtr, String estado) {
		this.horarioId = horarioId;
		this.codigo = codigo;
		this.descri = descri;
		this.minutoAlim = minutoAlim;
		this.horasLabo = horasLabo;
		this.tipo = tipo;
		this.inicioExtr = inicioExtr;
		this.estado = estado;
	}

	public Horario(Integer horarioId, String codigo, String descri,
			Integer minutoAlim, Integer horasLabo, String tipo,
			Integer inicioExtr, String estado, Set<HoraDeta> horaDetas,
			Set<EmplHoraDeta> emplHoraDetas, Set<HoraPlanDeta> horaPlanDetas) {
		this.horarioId = horarioId;
		this.codigo = codigo;
		this.descri = descri;
		this.minutoAlim = minutoAlim;
		this.horasLabo = horasLabo;
		this.tipo = tipo;
		this.inicioExtr = inicioExtr;
		this.estado = estado;
		this.horaDetas = horaDetas;
		this.emplHoraDetas = emplHoraDetas;
		this.horaPlanDetas = horaPlanDetas;
	}

	@Id
	@TableGenerator(name = "idHorario", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "horario", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idHorario")
	@Column(name = "horario_id", unique = true, nullable = false)
	public Integer getHorarioId() {
		return this.horarioId;
	}

	public void setHorarioId(Integer horarioId) {
		this.horarioId = horarioId;
	}

	@Column(name = "codigo", nullable = false, length = 4)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descri", nullable = false, length = 100)
	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	@Column(name = "minuto_alim", nullable = false)
	public Integer getMinutoAlim() {
		return this.minutoAlim;
	}

	public void setMinutoAlim(Integer minutoAlim) {
		this.minutoAlim = minutoAlim;
	}

	@Column(name = "horas_labo", nullable = false)
	public Integer getHorasLabo() {
		return this.horasLabo;
	}

	public void setHorasLabo(Integer horasLabo) {
		this.horasLabo = horasLabo;
	}

	@Column(name = "tipo", nullable = false, length = 12)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "inicio_extr", nullable = false)
	public Integer getInicioExtr() {
		return this.inicioExtr;
	}

	public void setInicioExtr(Integer inicioExtr) {
		this.inicioExtr = inicioExtr;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<HoraDeta> getHoraDetas() {
		return this.horaDetas;
	}

	public void setHoraDetas(Set<HoraDeta> horaDetas) {
		this.horaDetas = horaDetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<EmplHoraDeta> getEmplHoraDetas() {
		return this.emplHoraDetas;
	}

	public void setEmplHoraDetas(Set<EmplHoraDeta> emplHoraDetas) {
		this.emplHoraDetas = emplHoraDetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "horario")
	public Set<HoraPlanDeta> getHoraPlanDetas() {
		return this.horaPlanDetas;
	}

	public void setHoraPlanDetas(Set<HoraPlanDeta> horaPlanDetas) {
		this.horaPlanDetas = horaPlanDetas;
	}

}
