package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * HoraPlanDeta generated by hbm2java
 */
@Entity
@Table(name = "hora_plan_deta")
public class HoraPlanDeta implements java.io.Serializable {

	private Integer horaPlanDetaId;
	private HoraPlan horaPlan;
	private Horario horario;
	private Integer dia;

	private static final long serialVersionUID = -3436435348433225201L;

	public HoraPlanDeta() {
	}

	public HoraPlanDeta(Integer horaPlanDetaId, HoraPlan horaPlan,
			Horario horario, Integer dia) {
		this.horaPlanDetaId = horaPlanDetaId;
		this.horaPlan = horaPlan;
		this.horario = horario;
		this.dia = dia;
	}

	@Id
	@TableGenerator(name = "idHoraPlanDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "hora_plan_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idHoraPlanDeta")
	@Column(name = "hora_plan_deta_id", unique = true, nullable = false)
	public Integer getHoraPlanDetaId() {
		return this.horaPlanDetaId;
	}

	public void setHoraPlanDetaId(Integer horaPlanDetaId) {
		this.horaPlanDetaId = horaPlanDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hora_plan_id", nullable = false)
	public HoraPlan getHoraPlan() {
		return this.horaPlan;
	}

	public void setHoraPlan(HoraPlan horaPlan) {
		this.horaPlan = horaPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "horario_id", nullable = false)
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@Column(name = "dia", nullable = false)
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

}
