package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * HoraDeta generated by hbm2java
 */
@Entity
@Table(name = "hora_deta")
public class HoraDeta implements java.io.Serializable {

	private Integer horaDetaId;
	private Horario horario;
	private Date fechaHora;
	private Integer minutoTole;
	private String funcion;
	private Integer dias;

	private static final long serialVersionUID = -1289022422616826915L;

	public HoraDeta() {
	}

	public HoraDeta(Integer horaDetaId, Horario horario, Date fechaHora,
			Integer minutoTole, String funcion, Integer dias) {
		this.horaDetaId = horaDetaId;
		this.horario = horario;
		this.fechaHora = fechaHora;
		this.minutoTole = minutoTole;
		this.funcion = funcion;
		this.dias = dias;
	}

	@Id
	@TableGenerator(name = "idHoraDeta", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "hora_deta", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idHoraDeta")
	@Column(name = "hora_deta_id", unique = true, nullable = false)
	public Integer getHoraDetaId() {
		return this.horaDetaId;
	}

	public void setHoraDetaId(Integer horaDetaId) {
		this.horaDetaId = horaDetaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "horario_id", nullable = false)
	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_hora", nullable = false, length = 29)
	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	@Column(name = "minuto_tole", nullable = false)
	public Integer getMinutoTole() {
		return this.minutoTole;
	}

	public void setMinutoTole(Integer minutoTole) {
		this.minutoTole = minutoTole;
	}

	@Column(name = "funcion", nullable = false, length = 16)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

	@Column(name = "dias", nullable = false)
	public Integer getDias() {
		return this.dias;
	}

	public void setDias(Integer dias) {
		this.dias = dias;
	}

}
