package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.TableGenerator;

/**
 * KardVaca generated by hbm2java
 */
@Entity
@Table(name = "kard_vaca")
public class KardVaca implements java.io.Serializable {

	private Integer kardVacaId;
	private Ausencia ausencia;
	private EmplCargVaca emplCargVaca;

	private static final long serialVersionUID = -885650673439202210L;

	public KardVaca() {
	}

	public KardVaca(Integer kardVacaId) {
		this.kardVacaId = kardVacaId;
	}

	public KardVaca(Integer kardVacaId, Ausencia ausencia,
			EmplCargVaca emplCargVaca) {
		this.kardVacaId = kardVacaId;
		this.ausencia = ausencia;
		this.emplCargVaca = emplCargVaca;
	}

	@Id
	@TableGenerator(name = "idKardVaca", table = "secuencial", pkColumnName = "tabla", pkColumnValue = "kard_vaca", valueColumnName = "numero", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "idKardVaca")
	@Column(name = "kard_vaca_id", unique = true, nullable = false)
	public Integer getKardVacaId() {
		return this.kardVacaId;
	}

	public void setKardVacaId(Integer kardVacaId) {
		this.kardVacaId = kardVacaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ausencia_id")
	public Ausencia getAusencia() {
		return this.ausencia;
	}

	public void setAusencia(Ausencia ausencia) {
		this.ausencia = ausencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empl_carg_vaca_id")
	public EmplCargVaca getEmplCargVaca() {
		return this.emplCargVaca;
	}

	public void setEmplCargVaca(EmplCargVaca emplCargVaca) {
		this.emplCargVaca = emplCargVaca;
	}

}
