package ec.com.saolan.soem.asistencia.modelo;
// Generated 27/05/2020 20:38:02 by Hibernate Tools 5.2.0.Final

import java.util.HashSet;
import java.util.Set;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import ec.com.saolan.soem.nomina.modelo.AcciPers;
import ec.com.saolan.soem.nomina.modelo.AcciPersAuto;
import ec.com.saolan.soem.nomina.modelo.NomiDeta;
import ec.com.saolan.soem.nomina.modelo.Nomina;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * PersEmpl generated by hbm2java
 */
@Entity
@Table(name = "pers_empl")
public class PersEmpl implements java.io.Serializable {

	private Integer personaId;
	private String codigo;
	private String genero;
	private String estadoCivi;
	private String formaPago;
	private String banco;
	private String numeroCuen;
	private String estado;
	private Set<EmplCargVaca> emplCargVacas = new HashSet<EmplCargVaca>(0);
	private Set<EmplCont> emplConts = new HashSet<EmplCont>(0);
	private Set<EmplHoraDeta> emplHoraDetas = new HashSet<EmplHoraDeta>(0);
	private Set<EmplDisc> emplDiscs = new HashSet<EmplDisc>(0);
	private Set<NomiDeta> nomiMovis = new HashSet<NomiDeta>(0);
	private Set<AcciPers> acciPerses = new HashSet<AcciPers>(0);
	private Set<EmplHoraPlan> emplHoraPlans = new HashSet<EmplHoraPlan>(0);
	private Set<AcciPersAuto> acciAutos = new HashSet<AcciPersAuto>(0);
	private Set<AsisHora> asisHoras = new HashSet<AsisHora>(0);
	private Set<Nomina> nominas = new HashSet<Nomina>(0);
	private Set<EmplTitu> emplTitus = new HashSet<EmplTitu>(0);
	private Set<DepaCont> depaConts = new HashSet<DepaCont>(0);
	private Set<AuseAuto> auseAutos = new HashSet<AuseAuto>(0);
	private Set<Ausencia> ausencias = new HashSet<Ausencia>(0);

	private static final long serialVersionUID = -2189042215569656410L;

	public PersEmpl() {
	}

	public PersEmpl(Integer personaId, String codigo, String genero,
			String estadoCivi, String formaPago, String estado) {
		this.personaId = personaId;
		this.codigo = codigo;
		this.genero = genero;
		this.estadoCivi = estadoCivi;
		this.formaPago = formaPago;
		this.estado = estado;
	}

	public PersEmpl(Integer personaId, String codigo, String genero,
			String estadoCivi, String formaPago, String banco,
			String numeroCuen, String estado, Set<EmplCargVaca> emplCargVacas,
			Set<EmplCont> emplConts, Set<EmplHoraDeta> emplHoraDetas,
			Set<EmplDisc> emplDiscs, Set<NomiDeta> nomiMovis,
			Set<AcciPers> acciPerses, Set<EmplHoraPlan> emplHoraPlans,
			Set<AcciPersAuto> acciAutos, Set<AsisHora> asisHoras,
			Set<Nomina> nominas, Set<EmplTitu> emplTitus,
			Set<DepaCont> depaConts, Set<AuseAuto> auseAutos,
			Set<Ausencia> ausencias) {
		this.personaId = personaId;
		this.codigo = codigo;
		this.genero = genero;
		this.estadoCivi = estadoCivi;
		this.formaPago = formaPago;
		this.banco = banco;
		this.numeroCuen = numeroCuen;
		this.estado = estado;
		this.emplCargVacas = emplCargVacas;
		this.emplConts = emplConts;
		this.emplHoraDetas = emplHoraDetas;
		this.emplDiscs = emplDiscs;
		this.nomiMovis = nomiMovis;
		this.acciPerses = acciPerses;
		this.emplHoraPlans = emplHoraPlans;
		this.acciAutos = acciAutos;
		this.asisHoras = asisHoras;
		this.nominas = nominas;
		this.emplTitus = emplTitus;
		this.depaConts = depaConts;
		this.auseAutos = auseAutos;
		this.ausencias = ausencias;
	}

	@Id
	@GenericGenerator(name = "idPersEmpl", strategy = "foreign", parameters = @Parameter(name = "property", value = "persona"))
	@GeneratedValue(generator = "idPersEmpl")
	@Column(name = "persona_id", unique = true, nullable = false)
	public Integer getPersonaId() {
		return this.personaId;
	}

	public void setPersonaId(Integer personaId) {
		this.personaId = personaId;
	}

	@Column(name = "codigo", nullable = false, length = 32)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "genero", nullable = false, length = 16)
	public String getGenero() {
		return this.genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	@Column(name = "estado_civi", nullable = false, length = 16)
	public String getEstadoCivi() {
		return this.estadoCivi;
	}

	public void setEstadoCivi(String estadoCivi) {
		this.estadoCivi = estadoCivi;
	}

	@Column(name = "forma_pago", nullable = false, length = 16)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@Column(name = "banco", length = 32)
	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	@Column(name = "numero_cuen", length = 32)
	public String getNumeroCuen() {
		return this.numeroCuen;
	}

	public void setNumeroCuen(String numeroCuen) {
		this.numeroCuen = numeroCuen;
	}

	@Column(name = "estado", nullable = false, length = 12)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplCargVaca> getEmplCargVacas() {
		return this.emplCargVacas;
	}

	public void setEmplCargVacas(Set<EmplCargVaca> emplCargVacas) {
		this.emplCargVacas = emplCargVacas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplCont> getEmplConts() {
		return this.emplConts;
	}

	public void setEmplConts(Set<EmplCont> emplConts) {
		this.emplConts = emplConts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplHoraDeta> getEmplHoraDetas() {
		return this.emplHoraDetas;
	}

	public void setEmplHoraDetas(Set<EmplHoraDeta> emplHoraDetas) {
		this.emplHoraDetas = emplHoraDetas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplDisc> getEmplDiscs() {
		return this.emplDiscs;
	}

	public void setEmplDiscs(Set<EmplDisc> emplDiscs) {
		this.emplDiscs = emplDiscs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<NomiDeta> getNomiMovis() {
		return this.nomiMovis;
	}

	public void setNomiMovis(Set<NomiDeta> nomiMovis) {
		this.nomiMovis = nomiMovis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<AcciPers> getAcciPerses() {
		return this.acciPerses;
	}

	public void setAcciPerses(Set<AcciPers> acciPerses) {
		this.acciPerses = acciPerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplHoraPlan> getEmplHoraPlans() {
		return this.emplHoraPlans;
	}

	public void setEmplHoraPlans(Set<EmplHoraPlan> emplHoraPlans) {
		this.emplHoraPlans = emplHoraPlans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<AcciPersAuto> getAcciAutos() {
		return this.acciAutos;
	}

	public void setAcciAutos(Set<AcciPersAuto> acciAutos) {
		this.acciAutos = acciAutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<AsisHora> getAsisHoras() {
		return this.asisHoras;
	}

	public void setAsisHoras(Set<AsisHora> asisHoras) {
		this.asisHoras = asisHoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<Nomina> getNominas() {
		return this.nominas;
	}

	public void setNominas(Set<Nomina> nominas) {
		this.nominas = nominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<EmplTitu> getEmplTitus() {
		return this.emplTitus;
	}

	public void setEmplTitus(Set<EmplTitu> emplTitus) {
		this.emplTitus = emplTitus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<DepaCont> getDepaConts() {
		return this.depaConts;
	}

	public void setDepaConts(Set<DepaCont> depaConts) {
		this.depaConts = depaConts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<AuseAuto> getAuseAutos() {
		return this.auseAutos;
	}

	public void setAuseAutos(Set<AuseAuto> auseAutos) {
		this.auseAutos = auseAutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persEmpl")
	public Set<Ausencia> getAusencias() {
		return this.ausencias;
	}

	public void setAusencias(Set<Ausencia> ausencias) {
		this.ausencias = ausencias;
	}

}
